// Host-side unit tests for ClockPolicy.h (#192) — the pure decision logic
// behind clockTask's 1 Hz mode ticker and the strftime time formatting the
// clock mode and the /settings message stamp share.

#include <ArduinoFake.h>
#include <unity.h>

#include <cstdlib>
#include <ctime>

#include "../../ClockPolicy.h"
#include "../../DisplayCommand.h"

void setUp() {}
void tearDown() {}

// --- clockIsTimeSynced -------------------------------------------------------

static void test_time_sync_gate_boundary() {
  // v1's boot-wait constant: synced means time() reached 1000000000
  // (2001-09-09) — anything below is the un-synced epoch-1970 clock.
  TEST_ASSERT_FALSE(clockIsTimeSynced(0));
  TEST_ASSERT_FALSE(clockIsTimeSynced(999999999));
  TEST_ASSERT_TRUE(clockIsTimeSynced(1000000000));
  TEST_ASSERT_TRUE(clockIsTimeSynced(1783684800));
}

// --- formatDateTime ----------------------------------------------------------

static void useCetTimezone() {
  setenv("TZ", "CET-1CEST,M3.5.0,M10.5.0/3", 1);
  tzset();
}

static void test_format_clock_time_summer_cest() {
  useCetTimezone();
  // 2026-07-10 12:00:00 UTC — CEST is UTC+2.
  TEST_ASSERT_EQUAL_STRING(
      "14:00", formatDateTime(1783684800, CLOCK_FORMAT).c_str());
}

static void test_format_clock_time_winter_cet() {
  useCetTimezone();
  // 2026-01-10 12:00:00 UTC — CET is UTC+1.
  TEST_ASSERT_EQUAL_STRING(
      "13:00", formatDateTime(1768046400, CLOCK_FORMAT).c_str());
}

static void test_format_stamp_v1_shape() {
  useCetTimezone();
  // The /settings lastTimeReceivedMessageDateTime stamp, v1 format string.
  TEST_ASSERT_EQUAL_STRING(
      "10 Jul 26 14:00:00",
      formatDateTime(1783684800, "%d %b %y %H:%M:%S").c_str());
}

// --- decideClockTick ---------------------------------------------------------

static ClockTickInput clockModeInput() {
  ClockTickInput in;
  in.deviceMode = "clock";
  in.inputText = "HELLO";
  in.formattedTime = "12:05";
  in.timeSynced = true;
  in.displayBusy = false;
  in.displayCurrentText = "";
  in.lastQueued = "";
  return in;
}

static void test_clock_mode_enqueues_formatted_time() {
  ClockTickInput in = clockModeInput();
  ClockTickDecision d = decideClockTick(in);
  TEST_ASSERT_TRUE(d.enqueue);
  TEST_ASSERT_EQUAL_STRING("12:05", d.text.c_str());
}

static void test_clock_mode_dedups_same_minute() {
  // Steady state: the displayed text already IS this minute — one command
  // per minute, not one per second (v1's lastWrittenText gate, relocated).
  ClockTickInput in = clockModeInput();
  in.displayCurrentText = "12:05";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_clock_mode_minute_rollover_enqueues_once() {
  ClockTickInput in = clockModeInput();
  in.displayCurrentText = "12:05";
  in.formattedTime = "12:06";
  ClockTickDecision d = decideClockTick(in);
  TEST_ASSERT_TRUE(d.enqueue);
  TEST_ASSERT_EQUAL_STRING("12:06", d.text.c_str());
}

static void test_clock_mode_unsynced_holds_last_content() {
  // Deliberate v1 deviation: never flap epoch-1970 garbage. Until NTP
  // syncs, clock mode leaves whatever is on the display alone.
  ClockTickInput in = clockModeInput();
  in.timeSynced = false;
  in.formattedTime = "01:00";  // what strftime would say at epoch ~0
  in.displayCurrentText = "HELLO";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_text_mode_reshows_input_after_mode_switch() {
  // clock -> text switch: the display still shows the clock; the ticker is
  // the path that re-shows the retained message (v1 loop() parity).
  ClockTickInput in = clockModeInput();
  in.deviceMode = "text";
  in.displayCurrentText = "12:05";
  ClockTickDecision d = decideClockTick(in);
  TEST_ASSERT_TRUE(d.enqueue);
  TEST_ASSERT_EQUAL_STRING("HELLO", d.text.c_str());
}

static void test_text_mode_steady_state_is_silent() {
  ClockTickInput in = clockModeInput();
  in.deviceMode = "text";
  in.displayCurrentText = "HELLO";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_empty_text_never_enqueues() {
  // Boot with no message yet: blank stays blank (v1 parity) — and an empty
  // command must never be generated by the ticker.
  ClockTickInput in = clockModeInput();
  in.deviceMode = "text";
  in.inputText = "";
  in.displayCurrentText = "12:05";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_busy_display_defers_to_next_tick() {
  ClockTickInput in = clockModeInput();
  in.displayBusy = true;
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_unknown_mode_never_enqueues() {
  // Modes are validated at the web boundary; if something slips through the
  // ticker degrades to silence, not to a wrong command.
  ClockTickInput in = clockModeInput();
  in.deviceMode = "date";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_inflight_command_suppresses_reenqueue() {
  // Command queued last tick, worker hasn't executed it yet: the snapshot
  // is stale but lastQueued knows the command is in flight.
  ClockTickInput in = clockModeInput();
  in.displayCurrentText = "";  // stale
  in.lastQueued = "12:05";
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_decision_is_idempotent_for_queue_full_retry() {
  // Enqueue failed (queue full): the caller does NOT advance lastQueued, so
  // the identical input must keep asking for the same command next tick.
  ClockTickInput in = clockModeInput();
  ClockTickDecision first = decideClockTick(in);
  ClockTickDecision second = decideClockTick(in);
  TEST_ASSERT_TRUE(first.enqueue);
  TEST_ASSERT_TRUE(second.enqueue);
  TEST_ASSERT_EQUAL_STRING(first.text.c_str(), second.text.c_str());
}

// --- clockTickObserve --------------------------------------------------------

static void test_observe_clears_lastqueued_once_executed() {
  String lastQueued = "12:05";
  clockTickObserve(lastQueued, "12:05");
  TEST_ASSERT_EQUAL_STRING("", lastQueued.c_str());
}

static void test_observe_keeps_lastqueued_while_in_flight() {
  String lastQueued = "12:05";
  clockTickObserve(lastQueued, "HELLO");
  TEST_ASSERT_EQUAL_STRING("12:05", lastQueued.c_str());
}

static void test_long_message_reshow_survives_display_truncation() {
  // Review H1 regression: a message longer than the display (16 units) is
  // truncated by makeShowTextCommand, so every String entering the dedup
  // comparisons MUST be display-domain (pre-truncated). With that contract
  // held, the clock->text re-show converges instead of lastQueued sticking
  // forever on a raw 20-char string no snapshot can ever equal.
  String raw = "HELLO WORLD EVERYONE";  // 20 chars
  String shown = truncateForDisplay(raw);
  TEST_ASSERT_TRUE(shown.length() < raw.length());

  // Ticker re-shows the retained message after a clock interlude.
  ClockTickInput in = clockModeInput();
  in.deviceMode = "text";
  in.inputText = shown;  // glue stores display-domain text
  in.displayCurrentText = "12:05";
  ClockTickDecision d = decideClockTick(in);
  TEST_ASSERT_TRUE(d.enqueue);
  TEST_ASSERT_EQUAL_STRING(shown.c_str(), d.text.c_str());

  // The executed command's snapshot text now MATCHES lastQueued, so the
  // observe pass clears it and steady state is silent.
  String lastQueued = d.text;
  clockTickObserve(lastQueued, shown);
  TEST_ASSERT_EQUAL_STRING("", lastQueued.c_str());
  in.displayCurrentText = shown;
  in.lastQueued = lastQueued;
  TEST_ASSERT_FALSE(decideClockTick(in).enqueue);
}

static void test_reshow_allowed_after_catchup_and_overwrite() {
  // Full sequence: ticker queues 12:05 -> executed (observe clears) -> a
  // drain message overwrites the display -> the ticker may re-show 12:05.
  // Without the observe-clear, lastQueued would suppress it for the rest
  // of the minute.
  String lastQueued = "12:05";
  clockTickObserve(lastQueued, "12:05");  // executed
  ClockTickInput in = clockModeInput();
  in.displayCurrentText = "HELLO";  // drain overwrote mid-minute
  in.lastQueued = lastQueued;
  ClockTickDecision d = decideClockTick(in);
  TEST_ASSERT_TRUE(d.enqueue);
  TEST_ASSERT_EQUAL_STRING("12:05", d.text.c_str());
}

// ---------------------------------------------------------------------------

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_time_sync_gate_boundary);
  RUN_TEST(test_format_clock_time_summer_cest);
  RUN_TEST(test_format_clock_time_winter_cet);
  RUN_TEST(test_format_stamp_v1_shape);
  RUN_TEST(test_clock_mode_enqueues_formatted_time);
  RUN_TEST(test_clock_mode_dedups_same_minute);
  RUN_TEST(test_clock_mode_minute_rollover_enqueues_once);
  RUN_TEST(test_clock_mode_unsynced_holds_last_content);
  RUN_TEST(test_text_mode_reshows_input_after_mode_switch);
  RUN_TEST(test_text_mode_steady_state_is_silent);
  RUN_TEST(test_empty_text_never_enqueues);
  RUN_TEST(test_busy_display_defers_to_next_tick);
  RUN_TEST(test_unknown_mode_never_enqueues);
  RUN_TEST(test_inflight_command_suppresses_reenqueue);
  RUN_TEST(test_decision_is_idempotent_for_queue_full_retry);
  RUN_TEST(test_observe_clears_lastqueued_once_executed);
  RUN_TEST(test_observe_keeps_lastqueued_while_in_flight);
  RUN_TEST(test_long_message_reshow_survives_display_truncation);
  RUN_TEST(test_reshow_allowed_after_catchup_and_overwrite);
  return UNITY_END();
}
