"""Self-consistency gate for the generated new-twiboot image header (#499).

`firmware/v2/UnitBootloader/prebuilt/twiboot-new-progmem.h` is generated by
make_new_twiboot.py and committed, because the unit firmware embeds
`new_twiboot_image` as its boot-update target and BootSectionClassify.h keys off
the CRC constants. A hand-edit, a bad regen, or drift between the header's bytes
and its stated CRCs would ship a unit that writes the wrong bootloader, so this
gate pins — straight from the committed header + the committed fielded hex:

  * the embedded image is exactly 1024 bytes and its crc32 == NEW_TWIBOOT_CRC32,
  * new_twiboot_page7 == the last 128 bytes of the image (one source of truth),
  * the ABI marker (0x01, 0xFE) sits at 0x7FFE-0x7FFF,
  * do_spm is present at the page-7 start (not blank), DO_SPM_LEN bytes,
  * NEW_TWIBOOT_PAGE7_INSTALLED_CRC32 == crc32(fielded pages 0-6 + new page 7),
    the value BootSectionClassify maps to Page7Installed,
  * the new image actually differs from the fielded image (it is a new build).

Falsification (verify-guards-by-falsification): flip any asserted byte or CRC
and this must go red. Proven once during authoring.
"""

import pathlib
import re
import zlib

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
BOOT = REPO / "firmware/v2/UnitBootloader"
HEADER = BOOT / "prebuilt/twiboot-new-progmem.h"
FIELDED_HEX = BOOT / "prebuilt/twiboot-atmega328p-16mhz.hex"

BOOT_START = 0x7C00
IMAGE_LEN = 1024
PAGE_SIZE = 128
PAGES_0_6 = 7 * PAGE_SIZE  # 896


def _read_define(text, name):
    m = re.search(rf"#define\s+{name}\s+(0x[0-9a-fA-F]+|\d+)", text)
    assert m, f"{name} not found in header"
    return int(m.group(1), 0)


def _read_array(text, name):
    m = re.search(rf"{name}\[\d+\]\s*PROGMEM\s*=\s*{{(.*?)}};", text, re.S)
    assert m, f"array {name} not found in header"
    return bytes(int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1)))


def _ihex_boot_section(path):
    out = bytearray(b"\xff" * IMAGE_LEN)
    base = 0
    for line in path.read_text().splitlines():
        if not line.startswith(":"):
            continue
        b = bytes.fromhex(line[1:])
        n, addr, typ = b[0], (b[1] << 8) | b[2], b[3]
        if typ == 4:
            base = ((b[4] << 8) | b[5]) << 16
        elif typ == 2:
            base = ((b[4] << 8) | b[5]) << 4
        elif typ == 0:
            for i in range(n):
                a = base + addr + i
                if BOOT_START <= a < BOOT_START + IMAGE_LEN:
                    out[a - BOOT_START] = b[4 + i]
    return bytes(out)


@pytest.fixture(scope="module")
def header():
    return HEADER.read_text()


@pytest.fixture(scope="module")
def image(header):
    return _read_array(header, "new_twiboot_image")


def test_image_length_and_crc(header, image):
    assert len(image) == IMAGE_LEN
    assert (zlib.crc32(image) & 0xFFFFFFFF) == _read_define(header, "NEW_TWIBOOT_CRC32")


def test_masters_expect_the_image_the_units_install(header):
    # BOOT_CURRENT_CRC32 is what a row master judges a unit's bootloader
    # against (#520). The unit build asserts it equals NEW_TWIBOOT_CRC32; the
    # master trees never include the generated header, so it is pinned here.
    classify = (REPO / "firmware/v2/shared/BootSectionClassify.h").read_text()
    assert _read_define(classify, "BOOT_CURRENT_CRC32") == \
        _read_define(header, "NEW_TWIBOOT_CRC32")


def test_page7_matches_image_tail(header, image):
    page7 = _read_array(header, "new_twiboot_page7")
    assert len(page7) == PAGE_SIZE
    assert page7 == image[PAGES_0_6:]


def test_abi_marker(image):
    assert image[0x3FE] == 0x01
    assert image[0x3FF] == 0xFE


def test_do_spm_present(header, image):
    do_spm_len = _read_define(header, "NEW_TWIBOOT_DO_SPM_LEN")
    assert _read_define(header, "NEW_TWIBOOT_DO_SPM_ADDR") == 0x7F80
    do_spm = image[PAGES_0_6:PAGES_0_6 + do_spm_len]
    assert any(b != 0xFF for b in do_spm), "do_spm region is blank"
    # ends in `ret` (0x9508 -> 08 95 little-endian)
    assert do_spm[-2:] == bytes((0x08, 0x95))


def test_page7_installed_crc(header, image):
    fielded = _ihex_boot_section(FIELDED_HEX)
    page7_installed = fielded[:PAGES_0_6] + image[PAGES_0_6:]
    expected = zlib.crc32(page7_installed) & 0xFFFFFFFF
    assert expected == _read_define(header, "NEW_TWIBOOT_PAGE7_INSTALLED_CRC32")


def test_new_image_differs_from_fielded(image):
    fielded = _ihex_boot_section(FIELDED_HEX)
    assert image[:PAGES_0_6] != fielded[:PAGES_0_6], "new image equals fielded"


# --- the images the current one replaces (#548) ---------------------------------

PREV_HEX = BOOT / "prebuilt/twiboot-prev-e422a668.hex"
PREV2_HEX = BOOT / "prebuilt/twiboot-prev-081c2954.hex"
PREV3_HEX = BOOT / "prebuilt/twiboot-prev-c65e3dbf.hex"
CLASSIFY = REPO / "firmware/v2/shared/BootSectionClassify.h"


def test_previous_image_is_the_one_the_classifier_names():
    """Every unit carries this image until its boot section is updated. The
    classifier must name exactly these bytes, or those units read Unknown —
    corrupt on the masters, and refused by the updater."""
    prev = _ihex_boot_section(PREV_HEX)
    assert len(prev) == IMAGE_LEN
    assert zlib.crc32(prev) == _read_define(CLASSIFY.read_text(),
                                            "BOOT_PREV_NEW_CRC32")


def test_previous_image_shares_page_7_with_the_current_one():
    """Stage 2 rewrites pages 0-6 through do_spm in page 7 and never writes
    page 7. Going from the previous image to the current one by stage 2 alone
    is only correct while the two page 7s are the same bytes."""
    prev = _ihex_boot_section(PREV_HEX)
    image = _read_array(HEADER.read_text(), "new_twiboot_image")
    assert prev[PAGES_0_6:] == image[PAGES_0_6:]
    assert prev[:PAGES_0_6] != image[:PAGES_0_6]


def test_previous_image2_is_the_one_the_classifier_names():
    prev = _ihex_boot_section(PREV2_HEX)
    assert len(prev) == IMAGE_LEN
    assert zlib.crc32(prev) == _read_define(CLASSIFY.read_text(),
                                            "BOOT_PREV_NEW2_CRC32")


def test_previous_image2_shares_page_7_with_the_current_one():
    prev = _ihex_boot_section(PREV2_HEX)
    image = _read_array(HEADER.read_text(), "new_twiboot_image")
    assert prev[PAGES_0_6:] == image[PAGES_0_6:]
    assert prev[:PAGES_0_6] != image[:PAGES_0_6]


def test_previous_image3_is_the_one_the_classifier_names():
    prev = _ihex_boot_section(PREV3_HEX)
    assert len(prev) == IMAGE_LEN
    assert zlib.crc32(prev) == _read_define(CLASSIFY.read_text(),
                                            "BOOT_PREV_NEW3_CRC32")


def test_previous_image3_shares_page_7_with_the_current_one():
    prev = _ihex_boot_section(PREV3_HEX)
    image = _read_array(HEADER.read_text(), "new_twiboot_image")
    assert prev[PAGES_0_6:] == image[PAGES_0_6:]
    assert prev[:PAGES_0_6] != image[:PAGES_0_6]


def test_classifier_expects_the_current_image():
    text = CLASSIFY.read_text()
    assert _read_define(text, "BOOT_CURRENT_CRC32") == _read_define(
        HEADER.read_text(), "NEW_TWIBOOT_CRC32")
    all_prev = [
        _read_define(text, "BOOT_PREV_NEW_CRC32"),
        _read_define(text, "BOOT_PREV_NEW2_CRC32"),
        _read_define(text, "BOOT_PREV_NEW3_CRC32"),
    ]
    current = _read_define(text, "BOOT_CURRENT_CRC32")
    for p in all_prev:
        assert current != p
    assert len(set(all_prev)) == len(all_prev)
