"""PlatformIO pre-build script for the v2 rescue app (#195).

Generates:
  - RescueAssets.h: PROGMEM arrays for the rescue page + SparkMD5.
  - BuildVersion.h: #define for the current git commit.

Trimmed COPY of firmware/v2/Master/build_assets.py (repo convention: rescue
shares no build machinery with Master): no alphabet drift check, no favicon,
two assets total. data/md5.js is a verbatim copy of Master's — the ?md5=
wire contract needs client-side hashing on the self-contained rescue page.

Invoked by PlatformIO via `extra_scripts = pre:build_assets.py`.
"""

import gzip
import pathlib
import subprocess

ASSETS = [
    ("rescue.html", "RESCUE_HTML", True),
    ("md5.js",      "MD5_JS",      True),
]


def compress_asset(data: bytes) -> bytes:
    # mtime=0 keeps the gzip MTIME header field constant so two bakes of the
    # same source are byte-identical — the rescue bin must be reproducible
    # per commit (Master #168 rationale).
    return gzip.compress(data, 9, mtime=0)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        if (i + 1) % 16 == 0:
            fh.write("\n  ")
        else:
            fh.write(" ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


def version_tag(rev: str, dirty: bool) -> str:
    """Compose the GIT_REV tag: short hash, '-dirty' when the tree has
    uncommitted changes."""
    return f"{rev}-dirty" if dirty else rev


def build_version_header(tag: str) -> str:
    return (
        "// Auto-generated by build_assets.py — do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
    )


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    """(short rev, dirty?) for the repo containing project_dir. Falls back
    to ("unknown", False) if git isn't available."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def write_build_version(project_dir: pathlib.Path) -> None:
    rev, dirty = git_short_rev(project_dir)
    tag = version_tag(rev, dirty)
    (project_dir / "BuildVersion.h").write_text(
        build_version_header(tag), encoding="utf-8"
    )
    print(f"[build_assets] wrote BuildVersion.h  GIT_REV={tag}")


def build_header(project_dir: pathlib.Path) -> None:
    data_dir = project_dir / "data"
    output_header = project_dir / "RescueAssets.h"

    with output_header.open("w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        for filename, varname, gz in ASSETS:
            data = (data_dir / filename).read_bytes()
            if gz:
                gz_data = compress_asset(data)
                emit_array(fh, varname + "_GZ", gz_data)
                print(f"  {filename:<16} gz {len(data):>5} -> {len(gz_data):>5}")
            else:
                emit_array(fh, varname, data)
                print(f"  {filename:<16} raw {len(data):>5}")
    print(f"[build_assets] wrote {output_header.name}")


# PlatformIO invokes this file as a pre-build script, setting up a SCons
# env and calling Import() as a builtin. Run the bake only when invoked
# that way — plain `import build_assets` (pytest) is a no-op.
try:
    Import("env")  # noqa: F821  (provided by PlatformIO SCons env)
    _project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    write_build_version(_project_dir)
    build_header(_project_dir)

    # Post-build: stamped bin copy (rescue-<rev>.bin) so the file POSTed to
    # /firmware/rescue is self-describing — same convention as Master.
    _rev, _dirty = git_short_rev(_project_dir)
    _tag = version_tag(_rev, _dirty)

    def _stamp_firmware_filename(source, target, env):  # noqa: F821
        import shutil
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(f"rescue-{_tag}.bin")
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction(  # noqa: F821
        "$BUILD_DIR/${PROGNAME}.bin", _stamp_firmware_filename
    )
except NameError:
    pass
