"""PlatformIO pre-build script.

Generates:
  - WebAssets.h: PROGMEM arrays for the web UI assets and the bundled
    unit firmware binary.
  - BuildVersion.h: #defines for the current git commit (short hash +
    dirty flag), so the master firmware can report the version that
    was actually built into it.

The ESPMaster sketch now serves its UI directly from PROGMEM and auto-
installs unit firmware from PROGMEM too, so LittleFS is gone — that frees
the flash area that used to be the filesystem for OTA staging.

Invoked by PlatformIO via `extra_scripts = pre:build_assets.py`.
"""

import gzip
import pathlib
import subprocess

ASSETS = [
    ("index.html", "INDEX_HTML", True),
    ("script.js",  "SCRIPT_JS",  True),
    ("style.css",  "STYLE_CSS",  True),
    ("favicon.png","FAVICON_PNG",False),
]


def parse_intel_hex(path: pathlib.Path) -> bytes:
    """Return the raw bytes produced by applying every data record of an
    Intel-HEX file, filling gaps with 0xFF. Good enough for AVR sketches
    that are contiguous from 0."""
    out = bytearray()
    for line in path.read_text().splitlines():
        if not line.startswith(":"):
            continue
        byte_count = int(line[1:3], 16)
        addr = int(line[3:7], 16)
        rec_type = int(line[7:9], 16)
        if rec_type == 0x00:
            data = bytes.fromhex(line[9:9 + byte_count * 2])
            while len(out) < addr + byte_count:
                out.append(0xFF)
            out[addr:addr + byte_count] = data
        elif rec_type == 0x01:
            break
    return bytes(out)


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        if (i + 1) % 16 == 0:
            fh.write("\n  ")
        else:
            fh.write(" ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    """Return (short commit hash, dirty?) for the repo that contains
    project_dir. Falls back to ("unknown", False) if git isn't available."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def bundled_unit_rev(project_dir: pathlib.Path, fallback: str) -> str:
    """Return the rev the bundled unit-firmware.hex was built at.

    Read from ESPMaster/data/unit-firmware.rev if present (written by
    Unit/build_version.py). Falls back to the master's own rev so a missing
    sidecar degrades to the previous behaviour instead of blowing up.
    See issue #31.
    """
    sidecar = project_dir / "data" / "unit-firmware.rev"
    if sidecar.exists():
        return sidecar.read_text().strip() or fallback
    return fallback


def build_version_header(project_dir: pathlib.Path) -> None:
    rev, dirty = git_short_rev(project_dir)
    tag = f"{rev}-dirty" if dirty else rev
    unit_rev = bundled_unit_rev(project_dir, fallback=tag)
    output = project_dir / "BuildVersion.h"
    output.write_text(
        "// Auto-generated by build_assets.py — do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
        f'#define BUNDLED_UNIT_REV "{unit_rev}"\n'
    )
    print(f"[build_assets] wrote {output.name}  GIT_REV={tag}  BUNDLED_UNIT_REV={unit_rev}")


def build_header(project_dir: pathlib.Path) -> None:
    data_dir = project_dir / "data"
    output_header = project_dir / "WebAssets.h"

    lines_in = {}
    for filename, _, _ in ASSETS:
        lines_in[filename] = (data_dir / filename).read_bytes()

    unit_hex = data_dir / "unit-firmware.hex"
    unit_bin = pad_to_page(parse_intel_hex(unit_hex))

    with output_header.open("w") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        for filename, varname, gz in ASSETS:
            data = lines_in[filename]
            if gz:
                data = gzip.compress(data, 9)
                varname = varname + "_GZ"
            emit_array(fh, varname, data)
        emit_array(fh, "UNIT_FIRMWARE_BIN", unit_bin)

    print(f"[build_assets] wrote {output_header.name}")
    for filename, _, gz in ASSETS:
        data = lines_in[filename]
        if gz:
            print(f"  {filename:<16} gz {len(data):>5} -> {len(gzip.compress(data, 9)):>5}")
        else:
            print(f"  {filename:<16} raw {len(data):>5}")
    print(f"  unit-firmware    hex {unit_hex.stat().st_size:>5} -> bin {len(unit_bin):>5}")


def flash_size_label(env) -> str:
    """Derive a short '1m' / '4m' / '4m1m' tag from the env's ldscript so
    the stamped firmware filename reveals which flash layout it targets.
    Falls back to the env name if the ldscript doesn't match the standard
    pattern. Used by the post-build stamper below."""
    import re
    ldscript = env.GetProjectOption("board_build.ldscript", "")
    m = re.search(r"eagle\.flash\.([0-9]+m\d*m?)\.ld", ldscript)
    if m:
        return m.group(1)
    return env["PIOENV"]


# PlatformIO invokes this file as a pre-build script, setting up a SCons
# env and calling Import() as a builtin. Run the build only when invoked
# that way — plain `import build_assets` (e.g. from pytest) is a no-op.
try:
    Import("env")  # noqa: F821  (provided by PlatformIO SCons env)
    _project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    build_version_header(_project_dir)
    build_header(_project_dir)

    # Post-build: drop a copy of firmware.bin next to itself with the git
    # rev AND flash-size label in the filename so shipping / archiving is
    # self-describing across the 1 MB / 4 MB variants (issue #92).
    _rev, _dirty = git_short_rev(_project_dir)
    _tag = f"{_rev}-dirty" if _dirty else _rev
    _size = flash_size_label(env)  # noqa: F821

    def _stamp_firmware_filename(source, target, env):  # noqa: F821
        import shutil
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(f"firmware-{_tag}-{_size}.bin")
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction(  # noqa: F821
        "$BUILD_DIR/${PROGNAME}.bin", _stamp_firmware_filename
    )
except NameError:
    pass
