"""PlatformIO pre-build script for the Unit sketch.

Generates Unit/BuildVersion.h with the current git short rev so the unit
firmware can report its build over I2C via CMD_GET_VERSION (see Unit.ino).

The master compares this against its own GIT_REV to flag units running
outdated firmware. See issue #28.
"""

import pathlib
import subprocess


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def build_version_header(project_dir: pathlib.Path) -> None:
    rev, dirty = git_short_rev(project_dir)
    # Unit I2C response is a fixed 8 bytes. Keep the tag <= 8 chars so it
    # transmits verbatim; master truncates its own rev the same way on compare.
    tag = rev[:7]
    if dirty:
        tag = (tag + "*")[:8]
    output = project_dir / "BuildVersion.h"
    output.write_text(
        "// Auto-generated by build_version.py - do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
    )
    print(f"[build_version] wrote {output.name}  GIT_REV={tag}")


try:
    Import("env")  # noqa: F821 (PlatformIO SCons env)
    _project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    build_version_header(_project_dir)
except NameError:
    pass
