"""PlatformIO pre-build script for the ESP-01 follower (#298).

Trimmed copy of v1 ESPMaster's build_assets.py (no web assets — this
firmware serves no HTML). Generates:
  - UnitAssets.h: PROGMEM array of the bundled unit firmware binary
    (data/unit-firmware.hex, staged by flasher/make_manifest.py stage —
    MUST run between the Unit build and this build).
  - BuildVersion.h: GIT_REV + BUNDLED_UNIT_REV.
  - ApiIndexAsset.h: the whole GET /api reply as a PROGMEM array, built from
    ApiIndex.h's tables (#519). On the ESP-01 those tables' string literals
    and the buffer the reply was assembled in cost ~10 KB of an 82 KB RAM
    budget; served from flash they cost none.

Post-build it stamps the artifact as follower-<rev>.bin — the prefix is
what ota-flash.sh keys the ESP-01 platform on (never a valid payload for an
S3 master's /firmware/master and vice versa).
"""

import pathlib
import re
import subprocess


def parse_intel_hex(path: pathlib.Path) -> bytes:
    """Raw bytes from every data record, gaps filled with 0xFF (contiguous
    AVR sketches)."""
    out = bytearray()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith(":"):
            continue
        byte_count = int(line[1:3], 16)
        addr = int(line[3:7], 16)
        rec_type = int(line[7:9], 16)
        if rec_type == 0x00:
            data = bytes.fromhex(line[9:9 + byte_count * 2])
            while len(out) < addr + byte_count:
                out.append(0xFF)
            out[addr:addr + byte_count] = data
        elif rec_type == 0x01:
            break
    return bytes(out)


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        fh.write("\n  " if (i + 1) % 16 == 0 else " ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def bundled_unit_rev(project_dir: pathlib.Path, fallback: str) -> str:
    sidecar = project_dir / "data" / "unit-firmware.rev"
    if sidecar.exists():
        return sidecar.read_text(encoding="utf-8").strip() or fallback
    return fallback


def bundled_unit_equivalent_revs(project_dir: pathlib.Path) -> str:
    """Comma-separated revs whose unit image is byte-identical to the bundled
    one (#440) — see the Master copy for the full rationale. Absent sidecar →
    empty, i.e. bundle-rev equality only."""
    sidecar = project_dir / "data" / "unit-firmware.equiv"
    if not sidecar.exists():
        return ""
    lines = sidecar.read_text(encoding="utf-8").splitlines()
    return ",".join(s for s in (ln.strip() for ln in lines)
                    if s and not s.startswith("#"))


def build_version_header(project_dir: pathlib.Path) -> None:
    rev, dirty = git_short_rev(project_dir)
    tag = f"{rev}-dirty" if dirty else rev
    unit_rev = bundled_unit_rev(project_dir, fallback=tag)
    unit_equiv = bundled_unit_equivalent_revs(project_dir)
    output = project_dir / "BuildVersion.h"
    output.write_text(
        "// Auto-generated by build_assets.py — do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
        f'#define BUNDLED_UNIT_REV "{unit_rev}"\n'
        f'#define BUNDLED_UNIT_REV_EQUIV "{unit_equiv}"\n',
        encoding="utf-8",
    )
    print(f"[build_assets] wrote {output.name}  GIT_REV={tag}  "
          f"BUNDLED_UNIT_REV={unit_rev}  EQUIV=[{unit_equiv}]")


def build_unit_assets(project_dir: pathlib.Path) -> None:
    unit_hex = project_dir / "data" / "unit-firmware.hex"
    unit_bin = pad_to_page(parse_intel_hex(unit_hex))
    output = project_dir / "UnitAssets.h"
    with output.open("w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        emit_array(fh, "UNIT_FIRMWARE_BIN", unit_bin)
    print(f"[build_assets] wrote {output.name}  "
          f"unit-firmware hex {unit_hex.stat().st_size} -> bin {len(unit_bin)}")


_C_STRING = r'"((?:[^"\\]|\\.)*)"'


def _table_block(src: str, name: str) -> str:
    """The initialiser of `name[] = { ... };`, with // comments removed."""
    m = re.search(re.escape(name) + r"\[\]\s*=\s*\{(.*?)\n\};", src, re.DOTALL)
    if not m:
        raise ValueError(f"{name} table not found in ApiIndex.h")
    return re.sub(r"^\s*//.*$", "", m.group(1), flags=re.MULTILINE)


def api_index_json(project_dir: pathlib.Path) -> str:
    """The exact text buildApiJson() in ApiIndex.h produces, from the same
    tables. tests/test_api_index_asset.py compiles that function on the host
    and compares the two byte for byte, so this cannot drift from it."""
    src = (project_dir / "ApiIndex.h").read_text(encoding="utf-8")
    routes = re.findall(r"\{\s*%s\s*,\s*%s\s*,\s*%s\s*\}" % ((_C_STRING,) * 3),
                        _table_block(src, "API_ROUTES"))
    not_served = re.findall(_C_STRING, _table_block(src, "API_NOT_SERVED"))
    legend = re.findall(r"\{\s*%s\s*,\s*%s\s*\}" % ((_C_STRING,) * 2),
                        _table_block(src, "API_LEGEND"))
    if not routes or not legend:
        raise ValueError("ApiIndex.h tables parsed empty")
    for text in [f for row in routes + legend for f in row] + not_served:
        if "\\" in text or '"' in text:
            # buildApiJson() prints the literals verbatim; an escape would need
            # the same treatment on both sides.
            raise ValueError(f"escape sequence in an ApiIndex.h string: {text!r}")
    out = '{"routes":['
    out += ",".join('{"m":"%s","p":"%s","d":"%s"}' % r for r in routes)
    out += '],"notServed":['
    out += ",".join('"%s"' % p for p in not_served)
    out += '],"legend":{'
    out += ",".join('"%s":"%s"' % kv for kv in legend)
    out += "}}"
    return out


def build_api_index_asset(project_dir: pathlib.Path) -> None:
    body = api_index_json(project_dir).encode("utf-8")
    output = project_dir / "ApiIndexAsset.h"
    with output.open("w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        emit_array(fh, "API_INDEX_JSON", body)
    print(f"[build_assets] wrote {output.name}  {len(body)} bytes")


try:
    Import("env")  # noqa: F821  (provided by PlatformIO SCons env)
    _under_scons = True
except NameError:  # imported by a test, not run by the build
    _under_scons = False

if _under_scons:
    _project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    build_version_header(_project_dir)
    build_unit_assets(_project_dir)
    build_api_index_asset(_project_dir)

    _rev, _dirty = git_short_rev(_project_dir)
    _tag = f"{_rev}-dirty" if _dirty else _rev

    def _stamp_firmware_filename(source, target, env):  # noqa: F821
        import shutil
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(f"follower-{_tag}.bin")
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction(  # noqa: F821
        "$BUILD_DIR/${PROGNAME}.bin", _stamp_firmware_filename
    )
