"""PlatformIO pre-build script for SkeletonMaster.

Writes BuildVersion.h with the current git short-hash (plus a -dirty
suffix if the working tree has uncommitted changes). Same convention as
ESPMaster/build_assets.py so the stamped firmware-<rev>.bin naming and
the ota-master.sh regex line up for either firmware.

Invoked by PlatformIO via `extra_scripts = pre:build_version.py`.
"""

import pathlib
import subprocess

Import("env")  # noqa: F821 — PlatformIO SCons global


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def main() -> None:
    project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    rev, dirty = git_short_rev(project_dir)
    tag = f"{rev}-dirty" if dirty else rev
    output = project_dir / "BuildVersion.h"
    output.write_text(
        "// Auto-generated by build_version.py — do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
    )
    print(f"[build_version] wrote {output.name}  GIT_REV={tag}")


def stamp_firmware(source, target, env):  # noqa: ARG001
    """Copy firmware.bin to firmware-<rev>.bin after the build so the
    stamped filename lands next to the canonical one. Matches the naming
    convention ota-master.sh parses to derive ?v=."""
    import shutil
    build_dir = pathlib.Path(env.subst("$BUILD_DIR"))
    project_dir = pathlib.Path(env["PROJECT_DIR"])
    rev, dirty = git_short_rev(project_dir)
    tag = f"{rev}-dirty" if dirty else rev
    src = build_dir / "firmware.bin"
    if not src.exists():
        return
    dst = build_dir / f"firmware-{tag}.bin"
    shutil.copy2(src, dst)
    print(f"[build_version] copied firmware.bin -> {dst.name}")


main()
env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", stamp_firmware)  # noqa: F821
