"""PlatformIO pre-build script for the v2 master (#186).

Generates:
  - WebAssets.h: the bundled unit firmware image, as a PROGMEM array.
  - BuildVersion.h: #define for the current git commit (short hash +
    dirty flag), so the master firmware can report the version that
    was actually built into it.

The browser UI this script used to bake is gone — the device serves an HTTP
API and no pages, so the HTML/CSS/JS/favicon/portal blobs and the IANA
timezone table went with it. What remains is the one asset the firmware
itself needs: data/unit-firmware.hex (+ .rev sidecar, both committed —
staged by flashing/flasher/make_manifest.py) becomes UNIT_FIRMWARE_BIN in
WebAssets.h and BUNDLED_UNIT_REV in BuildVersion.h, for the over-I2C unit
reflash (#205). No filesystem image, no uploadfs step.

Invoked by PlatformIO via `extra_scripts = pre:build_assets.py`.
"""

import pathlib
import subprocess


def parse_intel_hex(path: pathlib.Path) -> bytes:
    """Return the raw bytes produced by applying every data record of an
    Intel-HEX file, filling gaps with 0xFF. Good enough for AVR sketches
    that are contiguous from 0."""
    out = bytearray()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith(":"):
            continue
        byte_count = int(line[1:3], 16)
        addr = int(line[3:7], 16)
        rec_type = int(line[7:9], 16)
        if rec_type == 0x00:
            data = bytes.fromhex(line[9:9 + byte_count * 2])
            while len(out) < addr + byte_count:
                out.append(0xFF)
            out[addr:addr + byte_count] = data
        elif rec_type == 0x01:
            break
    return bytes(out)


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


def bundled_unit_rev(project_dir: pathlib.Path, fallback: str) -> str:
    """Return the rev the bundled unit-firmware.hex was built at.

    Read from data/unit-firmware.rev if present (written by the
    make_manifest.py stage step). Falls back to the master's own rev so a
    missing sidecar degrades instead of blowing up (v1 #31).
    """
    sidecar = project_dir / "data" / "unit-firmware.rev"
    if sidecar.exists():
        return sidecar.read_text(encoding="utf-8").strip() or fallback
    return fallback


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        if (i + 1) % 16 == 0:
            fh.write("\n  ")
        else:
            fh.write(" ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


def git_short_rev(project_dir: pathlib.Path) -> tuple[str, bool]:
    """Return (short commit hash, dirty?) for the repo that contains
    project_dir. Falls back to ("unknown", False) if git isn't available."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def build_version_header(project_dir: pathlib.Path) -> None:
    rev, dirty = git_short_rev(project_dir)
    tag = f"{rev}-dirty" if dirty else rev
    unit_rev = bundled_unit_rev(project_dir, fallback=tag)
    output = project_dir / "BuildVersion.h"
    output.write_text(
        "// Auto-generated by build_assets.py — do not edit.\n"
        "#pragma once\n"
        f'#define GIT_REV "{tag}"\n'
        f'#define BUNDLED_UNIT_REV "{unit_rev}"\n',
        encoding="utf-8",
    )
    print(f"[build_assets] wrote {output.name}  GIT_REV={tag}  BUNDLED_UNIT_REV={unit_rev}")


def build_header(project_dir: pathlib.Path) -> None:
    data_dir = project_dir / "data"
    output_header = project_dir / "WebAssets.h"

    unit_hex = data_dir / "unit-firmware.hex"
    unit_bin = pad_to_page(parse_intel_hex(unit_hex))

    with output_header.open("w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        emit_array(fh, "UNIT_FIRMWARE_BIN", unit_bin)

    print(f"[build_assets] wrote {output_header.name}")


# PlatformIO invokes this file as a pre-build script, setting up a SCons
# env and calling Import() as a builtin. Run the build only when invoked
# that way — plain `import build_assets` (e.g. from pytest) is a no-op.
try:
    Import("env")  # noqa: F821  (provided by PlatformIO SCons env)
    _project_dir = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
    build_version_header(_project_dir)
    build_header(_project_dir)

    # Post-build: drop a copy of firmware.bin next to itself with the git
    # rev AND env name in the filename so shipping / archiving is
    # self-describing (v1 used the flash-size label; ESP32 boards have no
    # eagle ldscript, so the env name carries the layout identity here).
    _rev, _dirty = git_short_rev(_project_dir)
    _tag = f"{_rev}-dirty" if _dirty else _rev
    _env_name = env["PIOENV"]  # noqa: F821

    def _stamp_firmware_filename(source, target, env):  # noqa: F821
        import shutil
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(f"firmware-{_tag}-{_env_name}.bin")
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction(  # noqa: F821
        "$BUILD_DIR/${PROGNAME}.bin", _stamp_firmware_filename
    )
except NameError:
    pass
