"""Builds the operator page (#559/#574) from web/ into one HTML document.

The page is written as ES modules so its pure model can be imported by
`node --test`; a browser gets them joined into one script inside the page,
in the order of MODULES, with the import lines dropped and the `export`
keyword stripped. One document means one request to the board.

The firmware constants the page needs are generated from the headers into
web/gen/constants.js: never copied by hand.
"""

import pathlib
import re

# Order matters: a module comes after everything it imports.
MODULES = [
    "gen/constants.js",
    "model/format.js",
    "model/verdict.js",
    "model/wall.js",
    "app/dom.js",
    "app/api.js",
    "app/view_wall.js",
    "app/main.js",
]

_IMPORT = re.compile(r"^import\s[^;]*;\s*$", re.MULTILINE)
_EXPORT = re.compile(r"^export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)", re.MULTILINE)
_TOP_NAME = re.compile(r"^(?:async\s+)?(?:function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)", re.MULTILINE)


def _define(header_text: str, name: str) -> str:
    m = re.search(rf'#define\s+{name}\s+(?:"((?:[^"\\]|\\.)*)"|\(?(-?\d+)\)?)', header_text)
    if not m:
        raise ValueError(f"{name} #define not found")
    return m.group(1) if m.group(1) is not None else m.group(2)


def constants_js(project_dir: pathlib.Path) -> str:
    """The module the page's code imports its firmware constants from."""
    protocol = (project_dir.parent / "shared" / "SplitFlapProtocol.h").read_text(encoding="utf-8")
    alphabet = _define(protocol, "SFP_ALPHABET")
    if "\\" in alphabet or "'" in alphabet:
        raise ValueError("SFP_ALPHABET has a character the generator does not quote")
    return (
        "// Generated by web_bundle.py from the firmware headers — do not edit.\n"
        f"export const ALPHABET = '{alphabet}';\n"
        f"export const OFFSET_LIMIT_STEPS = {int(_define(protocol, 'SFP_OFFSET_LIMIT_STEPS'))};\n"
    )


def write_constants(project_dir: pathlib.Path) -> pathlib.Path:
    out = project_dir / "web" / "gen" / "constants.js"
    out.parent.mkdir(exist_ok=True)
    text = constants_js(project_dir)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
    return out


def bundle_js(web_dir: pathlib.Path) -> str:
    """Every module of MODULES as one script. Two modules declaring the same
    top-level name would silently shadow each other in the joined script, so
    that fails the build."""
    seen = {}
    parts = []
    for name in MODULES:
        source = (web_dir / name).read_text(encoding="utf-8")
        source = _EXPORT.sub("", _IMPORT.sub("", source))
        if re.search(r"^\s*(import|export)\b", source, re.MULTILINE):
            raise ValueError(f"{name}: an import or export the bundler does not understand")
        for top in _TOP_NAME.findall(source):
            if top in seen:
                raise ValueError(f"{name}: '{top}' is already declared in {seen[top]}")
            seen[top] = name
        parts.append(f"// --- {name}\n{source.strip()}\n")
    return "(() => {\n'use strict';\n" + "\n".join(parts) + "})();\n"


def build_page(project_dir: pathlib.Path) -> bytes:
    """web/index.html with the stylesheet and the joined script inside it."""
    web_dir = project_dir / "web"
    write_constants(project_dir)
    html = (web_dir / "index.html").read_text(encoding="utf-8")
    css = (web_dir / "style.css").read_text(encoding="utf-8")
    script = bundle_js(web_dir)
    if "</script" in script.lower() or "</style" in css.lower():
        raise ValueError("the page's script or stylesheet would end its own element")
    for marker in ("/*STYLE*/", "/*SCRIPT*/"):
        if html.count(marker) != 1:
            raise ValueError(f"web/index.html must hold {marker} exactly once")
    # Callables: a backslash in the page's own text is not a group reference.
    html = html.replace("/*STYLE*/", css).replace("/*SCRIPT*/", script)
    return html.encode("utf-8")
