// Static PROGMEM assets — split from WebEndpoints.cpp (#338); async-context
// rules in WebEndpoints.cpp's header.
//
// This TU is the ONLY WebAssets.h includer: the generated arrays have
// internal linkage, so a second include would duplicate every PROGMEM blob.
// Everything else reaches the bundled unit image through the
// webUnitFirmwareBin()/webUnitFirmwareBinLen() accessors below, and the
// portal page through the /wifi-setup route here.

#include "WebEndpoints.h"
#include "WebEndpointsInternal.h"

#include <ESPAsyncWebServer.h>

#include "Tasks.h"
#include "WebAssets.h"

// Serves a gzipped PROGMEM asset (v1 #159). Cache policy: PROGMEM assets
// only change via a master OTA, so the browser must revalidate every
// navigation or an OTA that swaps the UI would leave stale HTML/JS behind.
static void serveGzipAsset(AsyncWebServerRequest* request,
                           const char* contentType, const uint8_t* asset,
                           size_t assetLen) {
  AsyncWebServerResponse* resp =
      request->beginResponse(200, contentType, asset, assetLen);
  resp->addHeader("Content-Encoding", "gzip");
  resp->addHeader("Cache-Control", "no-cache");
  request->send(resp);
}

void webContentRegister(AsyncWebServer& server) {
  // --- static assets, all from PROGMEM (generated by build_assets.py) -----
  // The page: web/ joined into one document.
  server.on("/", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "text/html", PAGE_HTML_GZ, PAGE_HTML_GZ_LEN);
  });
  server.on("/favicon.png", HTTP_GET, [](AsyncWebServerRequest* request) {
    request->send(request->beginResponse(200, "image/png", FAVICON_PNG,
                                         FAVICON_PNG_LEN));
  });
  // Full IANA→POSIX timezone table (#252), baked from the vendored
  // posix_tz_db zones.csv; the page's Wall settings fetch it lazily.
  server.on("/tz.json", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "application/json", TZ_JSON_GZ, TZ_JSON_GZ_LEN);
  });

  // Portal page asset (#188) — served unconditionally; from the LAN it
  // doubles as a "move to another network" page. The wifi flow handlers
  // (/wifi/scan, /wifi/config) live in WebSettings.cpp; the
  // route is here because the page is a WebAssets.h blob.
  server.on("/wifi-setup", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "text/html", PORTAL_HTML_GZ, PORTAL_HTML_GZ_LEN);
  });
}

// Bundled unit firmware accessors (#205) — see the header comment above for
// why this TU is the only WebAssets.h includer. On the S3, PROGMEM is
// flash-mapped and directly readable, so the pointer works as a plain byte
// buffer.
const uint8_t* webUnitFirmwareBin() { return UNIT_FIRMWARE_BIN; }
size_t webUnitFirmwareBinLen() { return UNIT_FIRMWARE_BIN_LEN; }
