// Web endpoint registration for the v2 master (#186) — port of v1's
// ServiceWebEndpoints.ino onto the ESP32Async server stack.
//
// Async-context rule (v1 #150) carries over verbatim: handlers run in the
// async_tcp task. They may parse, validate, read state and respond — they
// must NOT mutate shared Strings, write NVS, or hold hardware buses.
// Mutating work is staged (pendingPost, pendingReboot) and drained from
// loop() via webEndpointsLoop().

#include "WebEndpoints.h"

#include <ESPAsyncWebServer.h>
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>

#include "BuildVersion.h"
#include "HelpersSerialHandling.h"
#include "PendingSettingsPost.h"
#include "SettingsJson.h"
#include "WebAssets.h"
#include "WebLog.h"

// Staged mutations, owned here; drained by webEndpointsLoop().
static PendingSettingsPost pendingPost;
static bool pendingReboot = false;
static uint32_t rebootRequestedAtMs = 0;

// Live state the read handlers render. Set once in webEndpointsInit();
// handlers only ever read (async-context rule). Held as TU-local statics
// rather than lambda-captured references so a handler can never outlive
// what it captured.
static MasterSettings* liveSettings = nullptr;
static String effectiveName;

// Cross-task guard. Unlike v1's single-core cooperative ESP8266, the
// handlers here run in the async_tcp FreeRTOS task while the drain runs in
// loopTask — Arduino Strings shared between them (pendingPost, *liveSettings,
// lastWrittenText) need real synchronization or a reader can see a buffer
// mid-free. A mutex (not a spinlock) on purpose: the critical sections
// allocate Strings and the drain writes NVS, neither of which is allowed
// inside portENTER_CRITICAL.
static SemaphoreHandle_t webStateMutex = nullptr;

struct WebStateLock {
  WebStateLock() { xSemaphoreTake(webStateMutex, portMAX_DELAY); }
  ~WebStateLock() { xSemaphoreGive(webStateMutex); }
  WebStateLock(const WebStateLock&) = delete;
  WebStateLock& operator=(const WebStateLock&) = delete;
};

// Last message accepted via POST / — the display service isn't ported yet,
// so this is a visible round-trip for the bench (echoed in /settings), not
// a claim that anything flapped.
static String lastWrittenText;

static const char* NOT_PORTED_MSG =
    "Not available on the v2 master yet (#58): this endpoint's backing "
    "service hasn't been ported.";

// Serves a gzipped PROGMEM asset (v1 #159). Cache policy: PROGMEM assets
// only change via a master OTA, so the browser must revalidate every
// navigation or an OTA that swaps the UI would leave stale HTML/JS behind.
static void serveGzipAsset(AsyncWebServerRequest* request,
                           const char* contentType, const uint8_t* asset,
                           size_t assetLen) {
  AsyncWebServerResponse* resp =
      request->beginResponse(200, contentType, asset, assetLen);
  resp->addHeader("Content-Encoding", "gzip");
  resp->addHeader("Cache-Control", "no-cache");
  request->send(resp);
}

static void registerNotPortedStub(AsyncWebServer& server, const char* path,
                                  WebRequestMethod method) {
  server.on(path, method, [](AsyncWebServerRequest* request) {
    request->send(501, "text/plain", NOT_PORTED_MSG);
  });
}

static const char* resetReasonString() {
  switch (esp_reset_reason()) {
    case ESP_RST_POWERON:   return "Power on";
    case ESP_RST_EXT:       return "External reset";
    case ESP_RST_SW:        return "Software reset";
    case ESP_RST_PANIC:     return "Exception/panic";
    case ESP_RST_INT_WDT:   return "Interrupt watchdog";
    case ESP_RST_TASK_WDT:  return "Task watchdog";
    case ESP_RST_WDT:       return "Other watchdog";
    case ESP_RST_DEEPSLEEP: return "Deep sleep wake";
    case ESP_RST_BROWNOUT:  return "Brownout";
    case ESP_RST_SDIO:      return "SDIO reset";
    default:                return "Unknown";
  }
}

void webEndpointsInit(AsyncWebServer& server, MasterSettings& settings,
                      SettingsStore& store,
                      const String& effectiveDeviceName) {
  (void)store;  // handlers never write the store; the loop drain does
  webStateMutex = xSemaphoreCreateMutex();
  liveSettings = &settings;
  effectiveName = effectiveDeviceName;

  // --- static assets, all from PROGMEM (generated by build_assets.py) -----
  server.on("/", HTTP_GET, [](AsyncWebServerRequest* request) {
    SerialPrintln(F("Request Home Page Received"));
    serveGzipAsset(request, "text/html", INDEX_HTML_GZ, INDEX_HTML_GZ_LEN);
  });
  server.on("/index.html", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "text/html", INDEX_HTML_GZ, INDEX_HTML_GZ_LEN);
  });
  server.on("/script.js", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "application/javascript", SCRIPT_JS_GZ,
                   SCRIPT_JS_GZ_LEN);
  });
  server.on("/md5.js", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "application/javascript", MD5_JS_GZ, MD5_JS_GZ_LEN);
  });
  server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest* request) {
    serveGzipAsset(request, "text/css", STYLE_CSS_GZ, STYLE_CSS_GZ_LEN);
  });
  server.on("/favicon.png", HTTP_GET, [](AsyncWebServerRequest* request) {
    request->send(request->beginResponse(200, "image/png", FAVICON_PNG,
                                         FAVICON_PNG_LEN));
  });

  // --- reads ---------------------------------------------------------------
  server.on("/settings", HTTP_GET, [](AsyncWebServerRequest* request) {
    SerialPrintln(F("Request for Settings Received"));
    SettingsJsonFields f;
    f.unitsAmount = UNITS_AMOUNT;  // arrays default per-slot until I2C slice
    {
      // Snapshot the shared Strings under the lock; serialize outside it.
      WebStateLock lock;
      f.alignment = liveSettings->alignment;
      f.flapSpeed = String(liveSettings->flapSpeed);
      f.deviceMode = liveSettings->deviceMode;
      f.timezonePosix = liveSettings->timezonePosix;
      f.deviceName = liveSettings->deviceName;
      f.effectiveDeviceName = effectiveName;
      f.mqttHost = liveSettings->mqttHost;
      f.mqttPort = String(liveSettings->mqttPort);
      f.mqttUser = liveSettings->mqttUser;
      f.mqttPasswordSet = liveSettings->mqttPassword.length() > 0;
      f.lastFlashResult = liveSettings->lastFlashResult;
      f.intendedVersion = liveSettings->intendedVersion;
      f.lastWrittenText = lastWrittenText;
    }
    f.mqttConnected = false;  // MQTT runtime is a later slice
    f.version = GIT_REV;
    f.sketchMd5 = ESP.getSketchMD5();
    f.otaReverted = false;  // boot-verdict logic lands with the OTA slice
    f.lastResetReason = resetReasonString();
    f.wifiSettingsResettable = false;  // WiFi slice flips this on
    request->send(200, "application/json", buildSettingsJson(f));
  });

  server.on("/health", HTTP_GET, [](AsyncWebServerRequest* request) {
    SerialPrintln(F("Request for Health Check Received"));
    request->send(200, "text/plain", "Healthy");
  });

  server.on("/log", HTTP_GET, [](AsyncWebServerRequest* request) {
    // Don't SerialPrintln here; every log request would otherwise stamp
    // itself into the buffer on every poll and drown out real activity.
    request->send(200, "text/plain", webLogRead());
  });

  // --- settings/message form (v1 wire contract) ----------------------------
  server.on("/", HTTP_POST, [](AsyncWebServerRequest* request) {
    SerialPrintln(F("Request Post of Form Received"));

    // All-or-nothing per POST: parse into a local post, merge only when
    // every provided field validated (v1 #128/#153 semantics, pure logic
    // in PendingSettingsPost.h — natively tested).
    PendingSettingsPost local;
    bool submissionError = false;

    int params = request->params();
    for (int i = 0; i < params; i++) {
      const AsyncWebParameter* p = request->getParam(i);
      if (!p->isPost()) continue;
      SettingsParamResult result =
          stageSettingsParam(local, p->name(), p->value());
      if (result == SettingsParamResult::Invalid) {
        SerialPrintln("Invalid value for '" + p->name() + "': " + p->value());
        submissionError = true;
      }
    }
    if (!settingsPostConsistent(local)) {
      SerialPrintln(F("Transient dwell provided without transient text."));
      submissionError = true;
    }

    // Per-card fetch() saves (#128) send ajax=1 and want a status code
    // instead of the classic redirect.
    bool isAjax = request->hasParam("ajax", true);

    if (submissionError) {
      SerialPrintln(F("Finished Processing Request with Error"));
      if (isAjax) request->send(400, "text/plain", F("invalid"));
      else request->redirect("/?invalid-submission=true");
      return;
    }

    // Verdict against the live values, then stage; the apply itself runs in
    // webEndpointsLoop(). Verdict + merge sit in one locked section so the
    // comparison can't race a half-applied post.
    bool needsReboot;
    bool deviceNameChanged;
    {
      WebStateLock lock;
      needsReboot = settingsPostNeedsReboot(local, *liveSettings);
      deviceNameChanged = local.deviceNameProvided &&
                          local.deviceName != liveSettings->deviceName;
      mergeSettingsPost(pendingPost, local);
    }

    SerialPrintln(F("Finished Processing Request Successfully"));
    if (isAjax) {
      request->send(200, "text/plain", needsReboot ? F("ok-reboot") : F("ok"));
    } else {
      request->redirect(deviceNameChanged ? "/?device-name-saved=true"
                        : needsReboot     ? "/?mqtt-saved=true"
                                          : "/");
    }
  });

  // POST, not GET (v1 #145): state-changing actions must not be triggerable
  // by a drive-by <img src> on the LAN.
  server.on("/reboot", HTTP_POST, [](AsyncWebServerRequest* request) {
    SerialPrintln(F("Request to Reboot Received"));
    request->send(200, "text/plain",
                  "Reboot pending — this takes a few seconds. Reload the home "
                  "page afterwards.");
    WebStateLock lock;
    pendingReboot = true;
    rebootRequestedAtMs = millis();
  });

  // --- v1 endpoints whose services aren't ported yet (#58 slices) ----------
  // Explicit 501s so a bench click yields a clear message instead of a
  // silent 404. Each stub is retired by the slice that ports its service.
  registerNotPortedStub(server, "/units/health", HTTP_GET);
  registerNotPortedStub(server, "/units/health/refresh", HTTP_POST);
  registerNotPortedStub(server, "/unit/offset", HTTP_GET);
  registerNotPortedStub(server, "/unit/offset", HTTP_POST);
  registerNotPortedStub(server, "/unit/jog", HTTP_POST);
  registerNotPortedStub(server, "/unit/home", HTTP_POST);
  registerNotPortedStub(server, "/unit/reboot", HTTP_POST);
  registerNotPortedStub(server, "/unit/identify", HTTP_POST);
  registerNotPortedStub(server, "/unit/set-address", HTTP_POST);
  registerNotPortedStub(server, "/unit/clear-address", HTTP_POST);
  registerNotPortedStub(server, "/stop", HTTP_POST);
  registerNotPortedStub(server, "/reflash-units", HTTP_POST);
  registerNotPortedStub(server, "/reset-units", HTTP_POST);
  registerNotPortedStub(server, "/firmware/master", HTTP_POST);
  registerNotPortedStub(server, "/firmware/recover-mark", HTTP_POST);
  registerNotPortedStub(server, "/firmware/ota-mode", HTTP_POST);
  registerNotPortedStub(server, "/debug/ota", HTTP_GET);
  registerNotPortedStub(server, "/mqtt/discover", HTTP_GET);
  registerNotPortedStub(server, "/mqtt/discover", HTTP_POST);
  registerNotPortedStub(server, "/reset-wifi", HTTP_POST);
}

void webEndpointsStart(AsyncWebServer& server) {
  server.begin();
  SerialPrintln(F("Web server started"));
}

void webEndpointsLoop(MasterSettings& settings, SettingsStore& store) {
  if (webStateMutex == nullptr) return;  // init hasn't run

  // The whole drain holds the mutex: applySettingsPost mutates the same
  // `settings` Strings GET /settings snapshots from the async task, and its
  // NVS writes are legal under a mutex (unlike a portENTER_CRITICAL
  // section). Worst case a handler blocks a few ms behind a flash commit.
  bool rebootDue = false;
  {
    WebStateLock lock;
    if (pendingPost.pending) {
      // Display-bound fields: parsed for wire-contract parity, consumed here
      // as a visible round-trip until the flap service slice lands.
      if (pendingPost.inputTextProvided) {
        lastWrittenText = pendingPost.inputText;
        SerialPrintln("Message staged (display service not ported yet, #58): " +
                      lastWrittenText);
      }
      if (pendingPost.transientTextProvided) {
        SerialPrintln("Transient text dropped (display service not ported yet, "
                      "#58): " + pendingPost.transientText);
      }
      applySettingsPost(pendingPost, settings, store);
    }
    // Small grace period so the HTTP response flushes before the restart.
    rebootDue = pendingReboot && millis() - rebootRequestedAtMs > 750;
  }

  if (rebootDue) {
    SerialPrintln(F("Rebooting..."));
    Serial.flush();
    ESP.restart();
  }
}
