"""PlatformIO pre-build script.

Generates WebAssets.h containing PROGMEM arrays for:
  - index.html, script.js, style.css (gzip-compressed)
  - favicon.png (raw)
  - unit-firmware.hex parsed into a raw 128-byte-page-aligned binary

The ESPMaster sketch now serves its UI directly from PROGMEM and auto-
installs unit firmware from PROGMEM too, so LittleFS is gone — that frees
the flash area that used to be the filesystem for OTA staging.

Invoked by PlatformIO via `extra_scripts = pre:build_assets.py`.
"""

import gzip
import pathlib

Import("env")  # noqa: F821  (provided by PlatformIO SCons env)

PROJECT_DIR = pathlib.Path(env["PROJECT_DIR"])  # noqa: F821
DATA_DIR = PROJECT_DIR / "data"
OUTPUT_HEADER = PROJECT_DIR / "WebAssets.h"

ASSETS = [
    ("index.html", "INDEX_HTML", True),
    ("script.js",  "SCRIPT_JS",  True),
    ("style.css",  "STYLE_CSS",  True),
    ("favicon.png","FAVICON_PNG",False),
]


def parse_intel_hex(path: pathlib.Path) -> bytes:
    """Return the raw bytes produced by applying every data record of an
    Intel-HEX file, filling gaps with 0xFF. Good enough for AVR sketches
    that are contiguous from 0."""
    out = bytearray()
    for line in path.read_text().splitlines():
        if not line.startswith(":"):
            continue
        byte_count = int(line[1:3], 16)
        addr = int(line[3:7], 16)
        rec_type = int(line[7:9], 16)
        if rec_type == 0x00:
            data = bytes.fromhex(line[9:9 + byte_count * 2])
            while len(out) < addr + byte_count:
                out.append(0xFF)
            out[addr:addr + byte_count] = data
        elif rec_type == 0x01:
            break
    return bytes(out)


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        if (i + 1) % 16 == 0:
            fh.write("\n  ")
        else:
            fh.write(" ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


def build_header() -> None:
    lines_in = {}
    for filename, _, _ in ASSETS:
        lines_in[filename] = (DATA_DIR / filename).read_bytes()

    unit_hex = DATA_DIR / "unit-firmware.hex"
    unit_bin = pad_to_page(parse_intel_hex(unit_hex))

    with OUTPUT_HEADER.open("w") as fh:
        fh.write("// Auto-generated by build_assets.py — do not edit.\n")
        fh.write("#pragma once\n\n#include <Arduino.h>\n\n")
        for filename, varname, gz in ASSETS:
            data = lines_in[filename]
            if gz:
                data = gzip.compress(data, 9)
                varname = varname + "_GZ"
            emit_array(fh, varname, data)
        emit_array(fh, "UNIT_FIRMWARE_BIN", unit_bin)

    print(f"[build_assets] wrote {OUTPUT_HEADER.name}")
    for filename, varname, gz in ASSETS:
        data = lines_in[filename]
        if gz:
            print(f"  {filename:<16} gz {len(data):>5} → {len(gzip.compress(data, 9)):>5}")
        else:
            print(f"  {filename:<16} raw {len(data):>5}")
    print(f"  unit-firmware    hex {unit_hex.stat().st_size:>5} → bin {len(unit_bin):>5}")


build_header()
