// Firmware OTA for the Nano units.
//
// The master ships a compiled unit binary in PROGMEM (UNIT_FIRMWARE_BIN,
// generated by build_assets.py from ESPMaster/data/unit-firmware.hex) and
// auto-flashes any unit the boot probe finds sitting in twiboot.
//
// High-level flow of flashUnitFromProgmem():
//   1. beginFirmwareFlash(addr): if the unit is running the sketch, send the
//      enter-bootloader I2C opcode and wait for twiboot to come up. Our
//      patched twiboot listens on the unit's DIP-derived address (not stock
//      0x29), so every twiboot call targets `addr` directly.
//   2. Stream UNIT_FIRMWARE_BIN one 128-byte page at a time via
//      producePageToTwiboot.
//   3. finishFirmwareFlash(): exit the bootloader, verify the unit came back
//      up at its normal address.
//
// Twiboot protocol: see the comment in UnitBootloader/main.c around line 150.

#include "WebAssets.h"  // for UNIT_FIRMWARE_BIN / UNIT_FIRMWARE_BIN_LEN

#define TWIBOOT_PAGE_SIZE       128
// ATmega328p flash is 32KB. Bootloader sits at 0x7C00; the rest is the app
// section we're allowed to write. Not currently enforced anywhere now that
// the only input is our own PROGMEM bundle, but kept for reference.
#define TWIBOOT_APP_MAX         0x7C00

volatile bool firmwareFlashInProgress = false;

// Minimal state for an in-flight PROGMEM flash. Previously this was a
// HexFlashState struct from HexFlashParser.h; that parser has been dropped
// along with the /firmware/unit web upload (see issue #23).
struct FirmwareFlashState {
  String   errorMsg;
  uint32_t totalBytesWritten;
};
static FirmwareFlashState flashState;
static uint8_t flashTargetI2cAddress = 0;
// Address used when talking to twiboot. Our DIP-patched bootloader listens on
// the unit's own I2C address (I2C_ADDRESS_BASE + DIP), so this is always set
// to the target unit's address at the start of a flash.
static uint8_t twibootAddr = 0;

// --- Twiboot I2C client --------------------------------------------------

static int twibootPing() {
  Wire.beginTransmission(twibootAddr);
  Wire.write((uint8_t)0x00);  // CMD_WAIT — resets twiboot's boot-window countdown
  return Wire.endTransmission();
}

static int twibootExit() {
  Wire.beginTransmission(twibootAddr);
  Wire.write((uint8_t)0x01);  // CMD_SWITCH_APPLICATION
  Wire.write((uint8_t)0x80);  // BOOTTYPE_APPLICATION
  return Wire.endTransmission();
}

// Queries twiboot chipinfo and checks it matches the ATmega328P. Populates
// `flashState.errorMsg` on mismatch.
static bool twibootVerifyChip() {
  Wire.beginTransmission(twibootAddr);
  Wire.write((uint8_t)0x02);  // CMD_ACCESS_MEMORY
  Wire.write((uint8_t)0x00);  // MEMTYPE_CHIPINFO
  Wire.write((uint8_t)0x00);
  Wire.write((uint8_t)0x00);
  if (Wire.endTransmission(false) != 0) {
    flashState.errorMsg = "Wire endTransmission failed reading chipinfo";
    return false;
  }
  uint8_t got = Wire.requestFrom(twibootAddr, (uint8_t)8);
  if (got != 8) {
    flashState.errorMsg = String("Chipinfo read returned ") + got + " bytes, expected 8";
    return false;
  }
  uint8_t sig0 = Wire.read(), sig1 = Wire.read(), sig2 = Wire.read();
  uint8_t pageSize = Wire.read();
  Wire.read(); Wire.read();  // flash size, unused
  Wire.read(); Wire.read();  // eeprom size, unused

  if (sig0 != 0x1E || sig1 != 0x95 || sig2 != 0x0F) {
    flashState.errorMsg = String("Unexpected chip signature ") + String(sig0, HEX) + " " +
                    String(sig1, HEX) + " " + String(sig2, HEX);
    return false;
  }
  if (pageSize != TWIBOOT_PAGE_SIZE) {
    flashState.errorMsg = String("Unexpected page size ") + pageSize;
    return false;
  }
  return true;
}

// Writes exactly one page (SPM_PAGESIZE = 128 bytes on ATmega328p).
static int twibootWriteFlashPage(uint16_t flashAddr, const uint8_t* page) {
  Wire.beginTransmission(twibootAddr);
  Wire.write((uint8_t)0x02);  // CMD_ACCESS_MEMORY
  Wire.write((uint8_t)0x01);  // MEMTYPE_FLASH
  Wire.write((uint8_t)((flashAddr >> 8) & 0xFF));
  Wire.write((uint8_t)(flashAddr & 0xFF));
  for (int i = 0; i < TWIBOOT_PAGE_SIZE; i++) {
    Wire.write(page[i]);
  }
  return Wire.endTransmission();
}

// --- Page flush -----------------------------------------------------------

// Spin-poll twiboot with CMD_WAIT until it ACKs again (meaning its async
// flash-write finished) or we give up. Clock stretching is disabled in our
// patched twiboot build, so during the ~4.5 ms page-program window twiboot
// simply NACKs. Return true if twiboot is ready, false on timeout.
static bool twibootWaitReady(uint16_t timeoutMs) {
  uint32_t deadline = millis() + timeoutMs;
  while ((int32_t)(millis() - deadline) < 0) {
    if (twibootPing() == 0) return true;
    delay(1);
  }
  return false;
}

// Drains one 128-byte page to twiboot.
static bool producePageToTwiboot(const uint8_t* page, uint16_t addr) {
  SerialPrint("Writing page 0x");
  SerialPrintln(String(addr, HEX));

  // Make sure twiboot is ready before hitting it with a 132-byte burst.
  if (!twibootWaitReady(100)) {
    flashState.errorMsg = String("twiboot not ready before page 0x") + String(addr, HEX);
    return false;
  }

  int status = twibootWriteFlashPage(addr, page);
  if (status != 0) {
    flashState.errorMsg = String("twibootWriteFlashPage failed at 0x") + String(addr, HEX) +
                          " status=" + String(status);
    return false;
  }

  // Wait for the async SPM cycle to finish. ~4.5 ms typical; 50 ms is
  // generous and still keeps the whole flash under a few seconds.
  if (!twibootWaitReady(50)) {
    flashState.errorMsg = String("twiboot stuck busy after page 0x") + String(addr, HEX);
    return false;
  }

  return true;
}

// --- Public API ----------------------------------------------------------

bool beginFirmwareFlash(uint8_t i2cAddress, String& error) {
  if (firmwareFlashInProgress) {
    error = "A flash is already in progress";
    return false;
  }

  SerialPrint("Firmware flash starting, target 0x");
  SerialPrintln(String(i2cAddress, HEX));

  // Our DIP-patched twiboot listens on the unit's own address, so that's
  // where every twiboot command must go.
  twibootAddr = i2cAddress;

  // If the unit is already sitting in twiboot, skip the reboot — sending
  // the enter-bootloader opcode to twiboot would be interpreted as the
  // unknown command 0x80. Probe with a chipinfo read.
  bool alreadyInBootloader = isUnitInBootloader((int)i2cAddress);

  if (!alreadyInBootloader) {
    int rebootStatus = rebootUnitToBootloader((int)i2cAddress);
    if (rebootStatus != 0) {
      error = String("Unit did not ack enter-bootloader (Wire status ") + rebootStatus + ")";
      return false;
    }
    SerialPrintln("Sent enter-bootloader opcode; waiting for twiboot");

    // Watchdog reset (~15ms) + twiboot init. 500ms is generous.
    delay(500);
  } else {
    SerialPrintln("Unit already in bootloader; skipping reboot");
  }

  bool bootloaderLive = false;
  for (int attempt = 0; attempt < 5; attempt++) {
    if (twibootPing() == 0) {
      bootloaderLive = true;
      break;
    }
    delay(100);
  }
  if (!bootloaderLive) {
    error = String("Twiboot not responding on 0x") + String(i2cAddress, HEX);
    return false;
  }
  SerialPrint("Twiboot responding on 0x");
  SerialPrintln(String(i2cAddress, HEX));

  if (!twibootVerifyChip()) {
    error = flashState.errorMsg;
    return false;
  }
  SerialPrintln("Chip signature OK (ATmega328P, page=128)");

  flashState.errorMsg          = "";
  flashState.totalBytesWritten = 0;
  flashTargetI2cAddress        = i2cAddress;

  firmwareFlashInProgress = true;
  return true;
}

bool finishFirmwareFlash(String& resultMsg) {
  if (!firmwareFlashInProgress) {
    resultMsg = "No flash in progress";
    return false;
  }

  uint8_t targetAddr = flashTargetI2cAddress;

  int exitStatus = twibootExit();
  if (exitStatus != 0) {
    resultMsg = String("Exit bootloader failed (Wire status ") + exitStatus + ")";
    firmwareFlashInProgress = false;
    return false;
  }

  uint32_t bytesWritten = flashState.totalBytesWritten;
  firmwareFlashInProgress = false;

  // Give the new sketch a couple of seconds to boot, then verify it
  // answers at its expected address.
  delay(2000);
  Wire.beginTransmission(targetAddr);
  int postFlashStatus = Wire.endTransmission();

  resultMsg = String("Flashed ") + bytesWritten + " bytes to 0x" + String(targetAddr, HEX);
  if (postFlashStatus == 0) {
    resultMsg += " — unit responding on its normal address";
    SerialPrintln(resultMsg);
  } else {
    resultMsg += String(" — WARNING: unit not responding post-flash (status ") + postFlashStatus + ")";
    SerialPrintln(resultMsg);
  }
  return true;
}

void abortFirmwareFlash(const String& reason) {
  SerialPrint("Aborting firmware flash: ");
  SerialPrintln(reason);
  firmwareFlashInProgress = false;
}

// Streams the PROGMEM-embedded unit firmware to twiboot one 128-byte page
// at a time.
bool flashUnitFromProgmem(uint8_t i2cAddress, String& resultMsg) {
  String beginError;
  if (!beginFirmwareFlash(i2cAddress, beginError)) {
    resultMsg = beginError;
    return false;
  }

  size_t pageCount = UNIT_FIRMWARE_BIN_LEN / TWIBOOT_PAGE_SIZE;
  uint8_t pageBuf[TWIBOOT_PAGE_SIZE];
  for (size_t pageIndex = 0; pageIndex < pageCount; pageIndex++) {
    memcpy_P(pageBuf, UNIT_FIRMWARE_BIN + pageIndex * TWIBOOT_PAGE_SIZE, TWIBOOT_PAGE_SIZE);
    uint16_t addr = (uint16_t)(pageIndex * TWIBOOT_PAGE_SIZE);
    if (!producePageToTwiboot(pageBuf, addr)) {
      resultMsg = String("PROGMEM flash failed: ") + flashState.errorMsg;
      abortFirmwareFlash("PROGMEM flash page error");
      return false;
    }
    flashState.totalBytesWritten += TWIBOOT_PAGE_SIZE;
  }

  return finishFirmwareFlash(resultMsg);
}

// Called from setup() after probeI2cBus() has populated detectedUnitStates.
// For every unit the probe flagged as being in bootloader mode, stream the
// PROGMEM-embedded unit binary. Best-effort: one failure doesn't abort the
// others.
extern int detectedUnitStates[];

void autoInstallFirmwareToBootloaderUnits() {
#if SERIAL_ENABLE == false && UNIT_CALLS_DISABLE == false
  int flashedCount = 0;
  for (int unitIndex = 0; unitIndex < UNITS_AMOUNT; unitIndex++) {
    if (detectedUnitStates[unitIndex] != 2 /* bootloader */) continue;

    int i2cAddress = toI2cAddress(unitIndex);
    SerialPrint("Auto-flashing unit at 0x");
    SerialPrint(String(i2cAddress, HEX));
    SerialPrint(" from PROGMEM (");
    SerialPrint(UNIT_FIRMWARE_BIN_LEN);
    SerialPrintln(" bytes)");

    String result;
    bool ok = flashUnitFromProgmem((uint8_t)i2cAddress, result);
    SerialPrint(ok ? "  [ok] " : "  [FAILED] ");
    SerialPrintln(result);
    if (ok) {
      //Just-provisioned unit is now running the sketch. Bump its state so
      //showMessage()/isDisplayMoving() stop skipping it.
      detectedUnitStates[unitIndex] = 1;
      flashedCount++;
    }
  }

  if (flashedCount > 0) {
    SerialPrint("Auto-install complete: ");
    SerialPrint(flashedCount);
    SerialPrintln(" unit(s) updated.");
  }
#endif
}

// Sends CMD_ENTER_BOOTLOADER to every unit the probe currently sees running
// the sketch (state == 1). With reprobeAfter=true, waits ~500 ms for their
// watchdog resets + twiboot init and re-runs probeI2cBus() so a subsequent
// autoInstallFirmwareToBootloaderUnits() will catch them. Returns the
// number of units that ACKed the reboot command.
int enterBootloaderAllDetected(bool reprobeAfter) {
  int rebooted = 0;
  for (int unitIndex = 0; unitIndex < UNITS_AMOUNT; unitIndex++) {
    if (detectedUnitStates[unitIndex] != 1) continue;
    int addr = toI2cAddress(unitIndex);
    if (rebootUnitToBootloader(addr) == 0) {
      rebooted++;
    }
  }
  if (rebooted > 0 && reprobeAfter) {
    //Watchdog reset (~15 ms) + twiboot init. 500 ms is generous.
    delay(500);
    probeI2cBus();
  }
  return rebooted;
}
