"""Build helpers shared by every firmware tree (#535).

Each tree's `build_assets.py` (a PlatformIO pre-build script) and the
host-side tools under `flashing/` import from here, so the unit image a
master embeds, the hash the bundle gate takes of it and the rev a binary
reports all come from one implementation. Tests: `buildtools/tests/`.

Lives outside `firmware/v2/shared/` on purpose: that directory is part of the
Unit source head, and a build-script edit must not re-label every unit.
"""

import gzip
import pathlib
import shutil
import subprocess

GENERATED_BANNER = "// Auto-generated by build_assets.py — do not edit.\n"


# --- Intel HEX -----------------------------------------------------------------

def ihex_to_memory(hex_path) -> dict:
    """{address: byte} for every data record of an Intel HEX file, honouring
    extended segment (02) and extended linear (04) address records and
    stopping at the end-of-file record."""
    mem = {}
    base = 0
    for line in pathlib.Path(hex_path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith(":"):
            continue
        raw = bytes.fromhex(line[1:])
        count, addr, rtype = raw[0], (raw[1] << 8) | raw[2], raw[3]
        data = raw[4:4 + count]
        if rtype == 0x00:
            for i, b in enumerate(data):
                mem[base + addr + i] = b
        elif rtype == 0x01:
            break
        elif rtype == 0x02:
            base = ((data[0] << 8) | data[1]) * 16
        elif rtype == 0x04:
            base = ((data[0] << 8) | data[1]) << 16
    return mem


def ihex_to_image(hex_path) -> bytes:
    """The program image from address 0 to the highest byte written, gaps
    filled with 0xFF (erased flash)."""
    mem = ihex_to_memory(hex_path)
    if not mem:
        return b""
    return bytes(mem.get(a, 0xFF) for a in range(max(mem) + 1))


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    """Pad with 0xFF to a whole number of flash pages (twiboot writes whole
    pages)."""
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


# --- generated headers -----------------------------------------------------------

def compress_asset(data: bytes) -> bytes:
    # mtime=0 keeps the gzip MTIME header field constant so two bakes of the
    # same source are byte-identical — a firmware bin must be reproducible
    # per commit (#168).
    return gzip.compress(data, 9, mtime=0)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        fh.write("\n  " if (i + 1) % 16 == 0 else " ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


# --- build identity ---------------------------------------------------------------

def git_short_rev(project_dir) -> tuple:
    """(short commit hash, dirty?) for the repo that contains project_dir.
    Falls back to ("unknown", False) if git isn't available."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def version_tag(rev: str, dirty: bool) -> str:
    """The GIT_REV tag: short hash, '-dirty' when the tree has uncommitted
    changes."""
    return f"{rev}-dirty" if dirty else rev


def build_tag(project_dir) -> str:
    return version_tag(*git_short_rev(project_dir))


def bundled_unit_rev(project_dir, fallback: str) -> str:
    """The rev the bundled unit-firmware.hex was built at, from
    data/unit-firmware.rev (written by make_manifest.py stage). Falls back to
    the tree's own rev so a missing sidecar degrades instead of blowing up."""
    sidecar = pathlib.Path(project_dir) / "data" / "unit-firmware.rev"
    if sidecar.exists():
        return sidecar.read_text(encoding="utf-8").strip() or fallback
    return fallback


def bundled_unit_equivalent_revs(project_dir) -> str:
    """Comma-separated revs whose unit image is byte-identical to the bundled
    one (#440), from data/unit-firmware.equiv (written by make_manifest.py
    stage, which keeps only entries still proven against the staged image).

    A unit reporting one of these was built at another commit but runs exactly
    our code, so it must not read OUTDATED — which, via ReflashPlan, would
    make it a reflash target. Absent sidecar → empty, i.e. bundle-rev equality
    only."""
    sidecar = pathlib.Path(project_dir) / "data" / "unit-firmware.equiv"
    if not sidecar.exists():
        return ""
    lines = sidecar.read_text(encoding="utf-8").splitlines()
    return ",".join(s for s in (ln.strip() for ln in lines)
                    if s and not s.startswith("#"))


def version_header_text(tag: str, unit_rev=None, unit_equiv=None) -> str:
    """BuildVersion.h: GIT_REV, plus the bundled unit identity for the trees
    that embed a unit image."""
    text = GENERATED_BANNER + "#pragma once\n" + f'#define GIT_REV "{tag}"\n'
    if unit_rev is not None:
        text += f'#define BUNDLED_UNIT_REV "{unit_rev}"\n'
        text += f'#define BUNDLED_UNIT_REV_EQUIV "{unit_equiv or ""}"\n'
    return text


def write_version_header(project_dir, with_unit_bundle: bool) -> str:
    """Writes BuildVersion.h and returns the build tag."""
    project_dir = pathlib.Path(project_dir)
    tag = build_tag(project_dir)
    unit_rev = unit_equiv = None
    if with_unit_bundle:
        unit_rev = bundled_unit_rev(project_dir, fallback=tag)
        unit_equiv = bundled_unit_equivalent_revs(project_dir)
    (project_dir / "BuildVersion.h").write_text(
        version_header_text(tag, unit_rev, unit_equiv), encoding="utf-8")
    line = f"[build_assets] wrote BuildVersion.h  GIT_REV={tag}"
    if with_unit_bundle:
        line += f"  BUNDLED_UNIT_REV={unit_rev}  EQUIV=[{unit_equiv}]"
    print(line)
    return tag


def unit_firmware_image(project_dir) -> bytes:
    """The bundled unit firmware as the page-padded binary a row master
    streams to twiboot."""
    return pad_to_page(ihex_to_image(
        pathlib.Path(project_dir) / "data" / "unit-firmware.hex"))


def stamp_firmware_bin(env, stamped_name: str) -> None:
    """Post-build: copy firmware.bin next to itself under a self-describing
    name (firmware-<rev>-<env>.bin / follower-<rev>.bin / rescue-<rev>.bin).
    The prefix is what ota-flash.sh keys the platform on."""
    def _stamp(source, target, env):
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(stamped_name)
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _stamp)
