"""Build helpers shared by every firmware tree (#535).

Each tree's `build_assets.py` (a PlatformIO pre-build script) and the
host-side tools under `flashing/` import from here, so the unit image a
master embeds, the hash the bundle gate takes of it and the rev a binary
reports all come from one implementation. Tests: `buildtools/tests/`.

Lives outside `firmware/v2/shared/` on purpose: that directory is part of the
Unit source head, and a build-script edit must not re-label every unit.
"""

import gzip
import pathlib
import shutil
import struct
import subprocess
import zlib

GENERATED_BANNER = "// Auto-generated by build_assets.py — do not edit.\n"


# --- Intel HEX -----------------------------------------------------------------

def ihex_to_memory(hex_path) -> dict:
    """{address: byte} for every data record of an Intel HEX file, honouring
    extended segment (02) and extended linear (04) address records and
    stopping at the end-of-file record."""
    mem = {}
    base = 0
    for line in pathlib.Path(hex_path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith(":"):
            continue
        raw = bytes.fromhex(line[1:])
        count, addr, rtype = raw[0], (raw[1] << 8) | raw[2], raw[3]
        data = raw[4:4 + count]
        if rtype == 0x00:
            for i, b in enumerate(data):
                mem[base + addr + i] = b
        elif rtype == 0x01:
            break
        elif rtype == 0x02:
            base = ((data[0] << 8) | data[1]) * 16
        elif rtype == 0x04:
            base = ((data[0] << 8) | data[1]) << 16
    return mem


def ihex_to_image(hex_path) -> bytes:
    """The program image from address 0 to the highest byte written, gaps
    filled with 0xFF (erased flash)."""
    mem = ihex_to_memory(hex_path)
    if not mem:
        return b""
    return bytes(mem.get(a, 0xFF) for a in range(max(mem) + 1))


def pad_to_page(data: bytes, page: int = 128) -> bytes:
    """Pad with 0xFF to a whole number of flash pages (twiboot writes whole
    pages)."""
    remainder = len(data) % page
    if remainder == 0:
        return data
    return data + b"\xFF" * (page - remainder)


# --- generated headers -----------------------------------------------------------

def compress_asset(data: bytes) -> bytes:
    # mtime=0 keeps the gzip MTIME header field constant so two bakes of the
    # same source are byte-identical — a firmware bin must be reproducible
    # per commit (#168).
    return gzip.compress(data, 9, mtime=0)


def emit_array(fh, name: str, data: bytes) -> None:
    fh.write(f"const uint8_t {name}[] PROGMEM = {{\n  ")
    for i, b in enumerate(data):
        fh.write(f"0x{b:02X},")
        fh.write("\n  " if (i + 1) % 16 == 0 else " ")
    fh.write("\n};\n")
    fh.write(f"const size_t {name}_LEN = {len(data)};\n\n")


# --- build identity ---------------------------------------------------------------

def git_short_rev(project_dir) -> tuple:
    """(short commit hash, dirty?) for the repo that contains project_dir.
    Falls back to ("unknown", False) if git isn't available."""
    try:
        rev = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ("unknown", False)
    try:
        dirty = bool(subprocess.check_output(
            ["git", "status", "--porcelain"],
            cwd=project_dir, stderr=subprocess.DEVNULL,
        ).decode().strip())
    except (FileNotFoundError, subprocess.CalledProcessError):
        dirty = False
    return (rev, dirty)


def version_tag(rev: str, dirty: bool) -> str:
    """The GIT_REV tag: short hash, '-dirty' when the tree has uncommitted
    changes."""
    return f"{rev}-dirty" if dirty else rev


def build_tag(project_dir) -> str:
    return version_tag(*git_short_rev(project_dir))


def bundled_unit_rev(project_dir, fallback: str) -> str:
    """The rev the bundled unit-firmware.hex was built at, from
    data/unit-firmware.rev (written by make_manifest.py stage). Falls back to
    the tree's own rev so a missing sidecar degrades instead of blowing up."""
    sidecar = pathlib.Path(project_dir) / "data" / "unit-firmware.rev"
    if sidecar.exists():
        return sidecar.read_text(encoding="utf-8").strip() or fallback
    return fallback


def bundled_unit_equivalent_revs(project_dir) -> str:
    """Comma-separated revs whose unit image is byte-identical to the bundled
    one (#440), from data/unit-firmware.equiv (written by make_manifest.py
    stage, which keeps only entries still proven against the staged image).

    A unit reporting one of these was built at another commit but runs exactly
    our code, so it must not read OUTDATED — which, via ReflashPlan, would
    make it a reflash target. Absent sidecar → empty, i.e. bundle-rev equality
    only."""
    sidecar = pathlib.Path(project_dir) / "data" / "unit-firmware.equiv"
    if not sidecar.exists():
        return ""
    lines = sidecar.read_text(encoding="utf-8").splitlines()
    return ",".join(s for s in (ln.strip() for ln in lines)
                    if s and not s.startswith("#"))


def version_header_text(tag: str, unit_rev=None, unit_equiv=None) -> str:
    """BuildVersion.h: GIT_REV, plus the bundled unit identity for the trees
    that embed a unit image."""
    text = GENERATED_BANNER + "#pragma once\n" + f'#define GIT_REV "{tag}"\n'
    if unit_rev is not None:
        text += f'#define BUNDLED_UNIT_REV "{unit_rev}"\n'
        text += f'#define BUNDLED_UNIT_REV_EQUIV "{unit_equiv or ""}"\n'
    return text


def write_version_header(project_dir, with_unit_bundle: bool) -> str:
    """Writes BuildVersion.h and returns the build tag."""
    project_dir = pathlib.Path(project_dir)
    tag = build_tag(project_dir)
    unit_rev = unit_equiv = None
    if with_unit_bundle:
        unit_rev = bundled_unit_rev(project_dir, fallback=tag)
        unit_equiv = bundled_unit_equivalent_revs(project_dir)
    (project_dir / "BuildVersion.h").write_text(
        version_header_text(tag, unit_rev, unit_equiv), encoding="utf-8")
    line = f"[build_assets] wrote BuildVersion.h  GIT_REV={tag}"
    if with_unit_bundle:
        line += f"  BUNDLED_UNIT_REV={unit_rev}  EQUIV=[{unit_equiv}]"
    print(line)
    return tag


def unit_firmware_image(project_dir) -> bytes:
    """The bundled unit firmware as the page-padded binary a row master
    streams to twiboot."""
    return pad_to_page(ihex_to_image(
        pathlib.Path(project_dir) / "data" / "unit-firmware.hex"))


def stamp_firmware_bin(env, stamped_name: str) -> None:
    """Post-build: copy firmware.bin next to itself under a self-describing
    name (firmware-<rev>-<env>.bin / follower-<rev>.bin / rescue-<rev>.bin).
    The prefix is what ota-flash.sh keys the platform on."""
    def _stamp(source, target, env):
        bin_path = pathlib.Path(str(target[0]))
        stamped = bin_path.with_name(stamped_name)
        shutil.copyfile(bin_path, stamped)
        print(f"[build_assets] copied {bin_path.name} -> {stamped.name}")

    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _stamp)


# --- ESP-01 OTA images (#540) ----------------------------------------------------
#
# The ESP-01 has one app area and no second slot: an upload is stored in the
# free space behind the running image and the bootloader (eboot) copies it
# down at reboot. eboot also unpacks a gzip upload, so the stored copy can be
# the compressed file. Everything below is that arithmetic, as the firmware
# and the ESP8266 core apply it.

# eagle.flash.1m.ld: _FS_start - 0x40200000. Running image + stored upload
# share this; EEPROM, rf-cal and the SDK's WiFi sectors sit above it.
ESP01_SKETCH_AREA = 0xFB000
ESP01_SECTOR = 0x1000
# A multipart POST carries its boundaries and part headers in Content-Length,
# and the follower compares that — not the file — against the free space.
OTA_MULTIPART_ALLOWANCE = 1024

# Layout of the file ota_gzip_image() writes: the 10-byte gzip header, then a
# 5-byte stored-block header, then the first bytes of the image verbatim.
# FollowerOtaImage.h reads the image header at this offset to refuse an image
# whose flash config differs from the running one — the core patches that
# into a plain upload but cannot reach inside a compressed one.
OTA_GZIP_IMAGE_OFFSET = 15
OTA_GZIP_STORED_LEN = 16


def ota_gzip_image(raw: bytes) -> bytes:
    """`raw` as a gzip file eboot can unpack, with the first
    OTA_GZIP_STORED_LEN bytes left uncompressed so the follower can inspect
    the image header before it accepts the upload."""
    if len(raw) < OTA_GZIP_STORED_LEN:
        raise ValueError("image shorter than its own header")
    head = raw[:OTA_GZIP_STORED_LEN]
    # MTIME 0: the same image always packs to the same bytes (and md5).
    out = b"\x1f\x8b\x08\x00" + b"\x00\x00\x00\x00" + b"\x02\xff"
    # Stored block, not final: BFINAL=0 BTYPE=00, LEN, ~LEN, data.
    out += b"\x00" + struct.pack("<HH", len(head), len(head) ^ 0xFFFF) + head
    deflate = zlib.compressobj(9, zlib.DEFLATED, -15)
    out += deflate.compress(raw[OTA_GZIP_STORED_LEN:]) + deflate.flush()
    out += struct.pack("<II", zlib.crc32(raw) & 0xFFFFFFFF, len(raw))
    return out


def _sector_ceil(n: int) -> int:
    return (n + ESP01_SECTOR - 1) & ~(ESP01_SECTOR - 1)


def ota_max_upload(running_len: int) -> int:
    """The largest request a follower running a `running_len`-byte image
    accepts: FollowerWeb.cpp's maxSketchSpace (free space minus one sector,
    floored to a sector)."""
    free = ESP01_SKETCH_AREA - _sector_ceil(running_len)
    if free < ESP01_SECTOR:
        return 0
    return (free - ESP01_SECTOR) & ~(ESP01_SECTOR - 1)


def ota_upload_fits(running_len: int, upload_len: int) -> bool:
    """The follower's 413 check: the request fits the free space."""
    return upload_len + OTA_MULTIPART_ALLOWANCE <= ota_max_upload(running_len)


def ota_stage_addr(running_len: int, upload_len: int, packed: bool) -> int:
    """Flash offset where the follower stores the upload. A plain image
    reserves the whole free space; a gzip one only its own sectors, which
    puts it at the top of the app area (FollowerOtaImage.h otaGzipReserve)."""
    reserve = ota_max_upload(running_len)
    if packed:
        reserve = min(reserve,
                      _sector_ceil(upload_len + OTA_MULTIPART_ALLOWANCE))
    return ESP01_SKETCH_AREA - reserve


def ota_gzip_unpack_fits(running_len: int, image_len: int,
                         gz_len: int) -> bool:
    """FollowerOtaImage.h otaGzipUnpackFits: the unpacked image ends below
    its stored copy, so eboot cannot overwrite input it has not read."""
    return _sector_ceil(image_len) <= ota_stage_addr(running_len, gz_len, True)


def ota_can_replace(running_len: int, image_len: int, upload_len: int) -> bool:
    """Would a follower running a `running_len` image accept this upload
    (`upload_len` < `image_len` means the gzip file)?"""
    if not ota_upload_fits(running_len, upload_len):
        return False
    if upload_len == image_len:
        return True
    return ota_gzip_unpack_fits(running_len, image_len, upload_len)


def ota_ceiling(ratio: float) -> int:
    """The largest image that can still replace an image of its own size
    when the upload is `ratio` times the image (1.0 = plain, ~0.7 = gzip).
    Past this a board running the image cannot take the next build."""
    def ok(n):
        return ota_can_replace(n, n, n if ratio >= 1.0 else round(n * ratio))
    lo, hi = 0, ESP01_SKETCH_AREA
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if ok(mid):
            lo = mid
        else:
            hi = mid - 1
    return lo


def ota_report(raw_len: int, gz_len: int) -> str:
    """One build-log line: where this image stands against both ceilings."""
    ratio = gz_len / raw_len
    plain, packed = ota_ceiling(1.0), ota_ceiling(ratio)
    return (f"image {raw_len} B, gzip {gz_len} B ({ratio:.1%}); "
            f"plain-OTA ceiling {plain} B ({plain - raw_len:+d}), "
            f"gzip-OTA ceiling {packed} B ({packed - raw_len:+d})")


def stamp_follower_images(env, tag: str) -> None:
    """Post-build: follower-<tag>.bin (the plain image) and
    follower-<tag>-gz.bin (the same image, gzip-packed for OTA), plus the
    ceiling report. Fails the build when the image could not replace itself
    over the air by either route — such a build strands every row it lands
    on."""
    def _stamp(source, target, env):
        bin_path = pathlib.Path(str(target[0]))
        raw = bin_path.read_bytes()
        packed = ota_gzip_image(raw)
        plain_name = f"follower-{tag}.bin"
        gz_name = f"follower-{tag}-gz.bin"
        shutil.copyfile(bin_path, bin_path.with_name(plain_name))
        bin_path.with_name(gz_name).write_bytes(packed)
        print(f"[build_assets] wrote {plain_name} + {gz_name}")
        print(f"[build_assets] {ota_report(len(raw), len(packed))}")
        if not ota_upload_fits(len(raw), len(raw)):
            print("[build_assets] WARNING: the plain image no longer fits "
                  "beside itself — rows can only take the -gz image")
        if not ota_can_replace(len(raw), len(raw), len(packed)):
            raise SystemExit(
                "[build_assets] follower image too large for OTA: a row "
                "running it could not take the next build")

    env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", _stamp)
