#!/usr/bin/env python3
"""Build the second-generation twiboot image for in-system update (#499).

The image is assembled from two independently built pieces so that page 7 has a
single source of truth (it is both the new image's page 7 and exactly the bytes
stage 1 writes into the fielded image's empty page 7):

  pages 0-6 (0x7C00-0x7F7F, 896 B) <- main.c built with -DSF_NEW_TWIBOOT=1
  page 7    (0x7F80-0x7FFF, 128 B) <- do_spm.S at 0x7F80 + 0xFF pad + ABI marker

Outputs (under this directory):
  twiboot-new-atmega328p-16mhz.hex   flashable ihex of the full boot section
  prebuilt/twiboot-new-progmem.h     canonical generated header: full 1024 B
                                     image + page-7 blob + CRC constants.
                                     Committed, and consumed by BOTH the unit
                                     firmware (embedded target image) and the
                                     simavr proof harness. Gated for
                                     self-consistency by
                                     tests/test_new_twiboot_image.py.

Run from firmware/v2/UnitBootloader with avr-gcc on PATH.
"""
import os
import subprocess
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
FIELDED_HEX = os.path.join(HERE, "prebuilt", "twiboot-atmega328p-16mhz.hex")
BOOT_START = 0x7C00
PAGE_SIZE = 128
PAGES_0_6 = 7 * PAGE_SIZE          # 896
PAGE7_OFF = PAGES_0_6              # 0x380
IMAGE_LEN = 8 * PAGE_SIZE          # 1024
ABI_VERSION = 0x01                 # generation marker, at 0x7FFE..0x7FFF

# Must match the Makefile's atmega328p CFLAGS_TARGET exactly so the lean build is
# byte-reproducible the same way the fielded image is.
CFLAGS = [
    "-pipe", "-g", "-Os", "-mmcu=atmega328p", "-Wall",
    "-fdata-sections", "-ffunction-sections",
    "-DBOOTLOADER_START=0x7C00",
    "-DF_CPU=16000000ULL", "-DTIMER_IRQFREQ_MS=16", "-DI2C_ADDRESS_BASE=1",
    "-DSF_NEW_TWIBOOT=1",
]
LDFLAGS = [
    "-Wl,--relax,--gc-sections,--section-start=.text=0x7C00",
    "-nostartfiles",
]


def run(cmd):
    subprocess.run(cmd, check=True, cwd=HERE)


def read_ihex_boot_section(path):
    """Return the boot section (0x7C00-0x7FFF) of an ihex as 1024 bytes, 0xFF
    where the hex has no data (e.g. the fielded image's blank page 7)."""
    out = bytearray(b"\xff" * (8 * PAGE_SIZE))
    base = 0
    for line in open(path):
        line = line.strip()
        if not line.startswith(":"):
            continue
        b = bytes.fromhex(line[1:])
        n, addr, typ = b[0], (b[1] << 8) | b[2], b[3]
        if typ == 4:
            base = ((b[4] << 8) | b[5]) << 16
        elif typ == 2:
            base = ((b[4] << 8) | b[5]) << 4
        elif typ == 0:
            for i in range(n):
                a = base + addr + i
                if BOOT_START <= a < BOOT_START + len(out):
                    out[a - BOOT_START] = b[4 + i]
    return bytes(out)


def build_pages_0_6():
    run(["avr-gcc", *CFLAGS, *LDFLAGS, "-o", "twiboot-new.elf", "main.c"])
    run(["avr-objcopy", "-j", ".text", "-j", ".data", "-O", "binary",
         "twiboot-new.elf", "twiboot-new-pages.bin"])
    data = open(os.path.join(HERE, "twiboot-new-pages.bin"), "rb").read()
    if len(data) > PAGES_0_6:
        sys.exit(f"ERROR: lean twiboot is {len(data)} B, exceeds the {PAGES_0_6} B "
                 f"available in pages 0-6 (would collide with page 7 / do_spm)")
    return data.ljust(PAGES_0_6, b"\xff")


def build_page7():
    run(["avr-gcc", "-mmcu=atmega328p", "-nostartfiles",
         "-Wl,--section-start=.text=0x7f80", "-o", "do_spm.elf", "do_spm.S"])
    run(["avr-objcopy", "-O", "binary", "-j", ".text", "do_spm.elf", "do_spm.bin"])
    do_spm = open(os.path.join(HERE, "do_spm.bin"), "rb").read()
    if len(do_spm) > PAGE_SIZE - 2:
        sys.exit(f"ERROR: do_spm is {len(do_spm)} B, no room for the ABI marker")
    page7 = bytearray(b"\xff" * PAGE_SIZE)
    page7[0:len(do_spm)] = do_spm
    page7[PAGE_SIZE - 2] = ABI_VERSION
    page7[PAGE_SIZE - 1] = (~ABI_VERSION) & 0xFF
    return bytes(page7), len(do_spm)


def emit_ihex(path, image):
    out = []
    # All addresses (0x7C00-0x7FFF) fit the 16-bit data-record field, so no
    # extended-linear-address record is needed.
    for off in range(0, len(image), 16):
        chunk = image[off:off + 16]
        addr = BOOT_START + off
        rec = [len(chunk), (addr >> 8) & 0xFF, addr & 0xFF, 0x00, *chunk]
        csum = (-sum(rec)) & 0xFF
        out.append(":" + bytes(rec + [csum]).hex())
    out.append(":00000001FF")
    open(path, "w").write("\n".join(out) + "\n")


def emit_c_header(path, image, page7, do_spm_len, page7_installed_crc):
    crc = zlib.crc32(image) & 0xFFFFFFFF
    with open(path, "w") as f:
        f.write("/* Generated by make_new_twiboot.py (#499) - do not edit.\n")
        f.write(" * Canonical embedded target image for the in-system twiboot\n")
        f.write(" * update: the unit firmware writes new_twiboot_image into its\n")
        f.write(" * boot section, and BootSectionClassify.h keys off these CRCs.\n")
        f.write(" * Self-consistency is gated by tests/test_new_twiboot_image.py. */\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("#ifdef __AVR__\n#include <avr/pgmspace.h>\n"
                "#else\n#define PROGMEM\n#endif\n\n")
        f.write("/* crc32 (zlib) of the full new boot section (0x7C00-0x7FFF). */\n")
        f.write(f"#define NEW_TWIBOOT_CRC32 0x{crc:08x}UL\n")
        f.write("/* crc32 of the post-stage-1 section: fielded pages 0-6 + the\n"
                " * new page 7. BootSectionClassify maps this to Page7Installed. */\n")
        f.write(f"#define NEW_TWIBOOT_PAGE7_INSTALLED_CRC32 0x{page7_installed_crc:08x}UL\n")
        f.write(f"#define NEW_TWIBOOT_BOOT_START 0x{BOOT_START:04x}\n")
        f.write(f"#define NEW_TWIBOOT_DO_SPM_ADDR 0x7F80\n")
        f.write(f"#define NEW_TWIBOOT_DO_SPM_LEN {do_spm_len}\n\n")
        f.write("/* Full boot section 0x7C00-0x7FFF, 1024 bytes (PROGMEM: read\n"
                " * with pgm_read_byte on AVR). */\n")
        f.write(f"static const uint8_t new_twiboot_image[{IMAGE_LEN}] PROGMEM = {{\n")
        for i in range(0, len(image), 12):
            f.write("  " + " ".join(f"0x{b:02x}," for b in image[i:i + 12]) + "\n")
        f.write("};\n\n")
        f.write("/* Page 7 only (0x7F80-0x7FFF): do_spm + pad + ABI marker. */\n")
        f.write(f"static const uint8_t new_twiboot_page7[{PAGE_SIZE}] PROGMEM = {{\n")
        for i in range(0, len(page7), 12):
            f.write("  " + " ".join(f"0x{b:02x}," for b in page7[i:i + 12]) + "\n")
        f.write("};\n")
    return crc


def main():
    pages = build_pages_0_6()
    page7, do_spm_len = build_page7()
    image = pages + page7
    assert len(image) == IMAGE_LEN

    # Post-stage-1 section: fielded pages 0-6 (unchanged) + the new page 7.
    fielded = read_ihex_boot_section(FIELDED_HEX)
    page7_installed = fielded[:PAGES_0_6] + page7
    page7_installed_crc = zlib.crc32(page7_installed) & 0xFFFFFFFF

    emit_ihex(os.path.join(HERE, "twiboot-new-atmega328p-16mhz.hex"), image)
    crc = emit_c_header(os.path.join(HERE, "prebuilt", "twiboot-new-progmem.h"),
                        image, page7, do_spm_len, page7_installed_crc)

    used = len(pages.rstrip(b"\xff"))
    print(f"pages 0-6 used: {used} B of {PAGES_0_6} B "
          f"({PAGES_0_6 - used} B headroom before page 7)")
    print(f"do_spm: {do_spm_len} B at 0x7F80; ABI marker 0x{ABI_VERSION:02x} at 0x7FFE")
    print(f"image: {len(image)} B, crc32 0x{crc:08x}")
    print(f"page7-installed crc32 0x{page7_installed_crc:08x}")


if __name__ == "__main__":
    main()
